/* Copyright © 2023 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/nsx.vmware.com/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeNsxV1alpha2 struct {
	*testing.Fake
}

func (c *FakeNsxV1alpha2) IPPools(namespace string) v1alpha2.IPPoolInterface {
	return &FakeIPPools{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeNsxV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
