/* Copyright © 2022 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/nsx.vmware.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubnetSets implements SubnetSetInterface
type FakeSubnetSets struct {
	Fake *FakeNsxV1alpha1
	ns   string
}

var subnetsetsResource = v1alpha1.SchemeGroupVersion.WithResource("subnetsets")

var subnetsetsKind = v1alpha1.SchemeGroupVersion.WithKind("SubnetSet")

// Get takes name of the subnetSet, and returns the corresponding subnetSet object, and an error if there is any.
func (c *FakeSubnetSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubnetSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(subnetsetsResource, c.ns, name), &v1alpha1.SubnetSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetSet), err
}

// List takes label and field selectors, and returns the list of SubnetSets that match those selectors.
func (c *FakeSubnetSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubnetSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(subnetsetsResource, subnetsetsKind, c.ns, opts), &v1alpha1.SubnetSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SubnetSetList{ListMeta: obj.(*v1alpha1.SubnetSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.SubnetSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested subnetSets.
func (c *FakeSubnetSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(subnetsetsResource, c.ns, opts))

}

// Create takes the representation of a subnetSet and creates it.  Returns the server's representation of the subnetSet, and an error, if there is any.
func (c *FakeSubnetSets) Create(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.CreateOptions) (result *v1alpha1.SubnetSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(subnetsetsResource, c.ns, subnetSet), &v1alpha1.SubnetSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetSet), err
}

// Update takes the representation of a subnetSet and updates it. Returns the server's representation of the subnetSet, and an error, if there is any.
func (c *FakeSubnetSets) Update(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.UpdateOptions) (result *v1alpha1.SubnetSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(subnetsetsResource, c.ns, subnetSet), &v1alpha1.SubnetSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSubnetSets) UpdateStatus(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.UpdateOptions) (*v1alpha1.SubnetSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(subnetsetsResource, "status", c.ns, subnetSet), &v1alpha1.SubnetSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetSet), err
}

// Delete takes name of the subnetSet and deletes it. Returns an error if one occurs.
func (c *FakeSubnetSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(subnetsetsResource, c.ns, name, opts), &v1alpha1.SubnetSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubnetSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(subnetsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SubnetSetList{})
	return err
}

// Patch applies the patch and returns the patched subnetSet.
func (c *FakeSubnetSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubnetSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(subnetsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SubnetSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetSet), err
}
