/* Copyright © 2022 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/nsx.vmware.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubnetPorts implements SubnetPortInterface
type FakeSubnetPorts struct {
	Fake *FakeNsxV1alpha1
	ns   string
}

var subnetportsResource = v1alpha1.SchemeGroupVersion.WithResource("subnetports")

var subnetportsKind = v1alpha1.SchemeGroupVersion.WithKind("SubnetPort")

// Get takes name of the subnetPort, and returns the corresponding subnetPort object, and an error if there is any.
func (c *FakeSubnetPorts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubnetPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(subnetportsResource, c.ns, name), &v1alpha1.SubnetPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetPort), err
}

// List takes label and field selectors, and returns the list of SubnetPorts that match those selectors.
func (c *FakeSubnetPorts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubnetPortList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(subnetportsResource, subnetportsKind, c.ns, opts), &v1alpha1.SubnetPortList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SubnetPortList{ListMeta: obj.(*v1alpha1.SubnetPortList).ListMeta}
	for _, item := range obj.(*v1alpha1.SubnetPortList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested subnetPorts.
func (c *FakeSubnetPorts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(subnetportsResource, c.ns, opts))

}

// Create takes the representation of a subnetPort and creates it.  Returns the server's representation of the subnetPort, and an error, if there is any.
func (c *FakeSubnetPorts) Create(ctx context.Context, subnetPort *v1alpha1.SubnetPort, opts v1.CreateOptions) (result *v1alpha1.SubnetPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(subnetportsResource, c.ns, subnetPort), &v1alpha1.SubnetPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetPort), err
}

// Update takes the representation of a subnetPort and updates it. Returns the server's representation of the subnetPort, and an error, if there is any.
func (c *FakeSubnetPorts) Update(ctx context.Context, subnetPort *v1alpha1.SubnetPort, opts v1.UpdateOptions) (result *v1alpha1.SubnetPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(subnetportsResource, c.ns, subnetPort), &v1alpha1.SubnetPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetPort), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSubnetPorts) UpdateStatus(ctx context.Context, subnetPort *v1alpha1.SubnetPort, opts v1.UpdateOptions) (*v1alpha1.SubnetPort, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(subnetportsResource, "status", c.ns, subnetPort), &v1alpha1.SubnetPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetPort), err
}

// Delete takes name of the subnetPort and deletes it. Returns an error if one occurs.
func (c *FakeSubnetPorts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(subnetportsResource, c.ns, name, opts), &v1alpha1.SubnetPort{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubnetPorts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(subnetportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SubnetPortList{})
	return err
}

// Patch applies the patch and returns the patched subnetPort.
func (c *FakeSubnetPorts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubnetPort, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(subnetportsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SubnetPort{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetPort), err
}
