/* Copyright © 2022 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/nsx.vmware.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVPCs implements VPCInterface
type FakeVPCs struct {
	Fake *FakeNsxV1alpha1
	ns   string
}

var vpcsResource = v1alpha1.SchemeGroupVersion.WithResource("vpcs")

var vpcsKind = v1alpha1.SchemeGroupVersion.WithKind("VPC")

// Get takes name of the vPC, and returns the corresponding vPC object, and an error if there is any.
func (c *FakeVPCs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VPC, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vpcsResource, c.ns, name), &v1alpha1.VPC{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPC), err
}

// List takes label and field selectors, and returns the list of VPCs that match those selectors.
func (c *FakeVPCs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VPCList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vpcsResource, vpcsKind, c.ns, opts), &v1alpha1.VPCList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VPCList{ListMeta: obj.(*v1alpha1.VPCList).ListMeta}
	for _, item := range obj.(*v1alpha1.VPCList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vPCs.
func (c *FakeVPCs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vpcsResource, c.ns, opts))

}

// Create takes the representation of a vPC and creates it.  Returns the server's representation of the vPC, and an error, if there is any.
func (c *FakeVPCs) Create(ctx context.Context, vPC *v1alpha1.VPC, opts v1.CreateOptions) (result *v1alpha1.VPC, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vpcsResource, c.ns, vPC), &v1alpha1.VPC{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPC), err
}

// Update takes the representation of a vPC and updates it. Returns the server's representation of the vPC, and an error, if there is any.
func (c *FakeVPCs) Update(ctx context.Context, vPC *v1alpha1.VPC, opts v1.UpdateOptions) (result *v1alpha1.VPC, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vpcsResource, c.ns, vPC), &v1alpha1.VPC{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPC), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVPCs) UpdateStatus(ctx context.Context, vPC *v1alpha1.VPC, opts v1.UpdateOptions) (*v1alpha1.VPC, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vpcsResource, "status", c.ns, vPC), &v1alpha1.VPC{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPC), err
}

// Delete takes name of the vPC and deletes it. Returns an error if one occurs.
func (c *FakeVPCs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vpcsResource, c.ns, name, opts), &v1alpha1.VPC{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVPCs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vpcsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VPCList{})
	return err
}

// Patch applies the patch and returns the patched vPC.
func (c *FakeVPCs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VPC, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vpcsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VPC{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPC), err
}
