# golangci-lint configuration used for CI
linters-settings:
  goimports:
    local-prefixes: github.com/vmware-tanzu/nsx-operator
  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 0.8
    rules:
      - name: unreachable-code
      - name: errorf
      - name: range
      - name: superfluous-else
      - name: var-declaration
      - name: duplicated-imports

linters:
  disable-all: true
  enable:
    - misspell
    - gofmt
    - unused
    - staticcheck
    - gosec
    - goimports
    - govet
    - revive

issues:
  exclude-files:
   - third_party/
   - pkg/client/
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019: lbs.RelaxScaleValidation"