codecov:
  branch: main
  require_ci_to_pass: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1
  show_carryforward_flags: true

github_checks:
  annotations: true

coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        only_pulls: false
    project:
      default:
        target: auto
        threshold: 0.3%

flag_management:
  default_rules:
    carryforward: true

ignore:
  - "**/test/*.go"
