//go:build !ignore_autogenerated

/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateSubnetPortSpec) DeepCopyInto(out *CreateSubnetPortSpec) {
	*out = *in
	if in.SubnetIPReservations != nil {
		in, out := &in.SubnetIPReservations, &out.SubnetIPReservations
		*out = make([]NamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
	out.SubnetPort = in.SubnetPort
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateSubnetPortSpec.
func (in *CreateSubnetPortSpec) DeepCopy() *CreateSubnetPortSpec {
	if in == nil {
		return nil
	}
	out := new(CreateSubnetPortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateSubnetPortStatus) DeepCopyInto(out *CreateSubnetPortStatus) {
	*out = *in
	out.SubnetPort = in.SubnetPort
	if in.SubnetIPReservations != nil {
		in, out := &in.SubnetIPReservations, &out.SubnetIPReservations
		*out = make([]NamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateSubnetPortStatus.
func (in *CreateSubnetPortStatus) DeepCopy() *CreateSubnetPortStatus {
	if in == nil {
		return nil
	}
	out := new(CreateSubnetPortStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveIPAddressAllocationSpec) DeepCopyInto(out *MoveIPAddressAllocationSpec) {
	*out = *in
	out.Source = in.Source
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveIPAddressAllocationSpec.
func (in *MoveIPAddressAllocationSpec) DeepCopy() *MoveIPAddressAllocationSpec {
	if in == nil {
		return nil
	}
	out := new(MoveIPAddressAllocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoveIPAddressAllocationStatus) DeepCopyInto(out *MoveIPAddressAllocationStatus) {
	*out = *in
	out.Source = in.Source
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoveIPAddressAllocationStatus.
func (in *MoveIPAddressAllocationStatus) DeepCopy() *MoveIPAddressAllocationStatus {
	if in == nil {
		return nil
	}
	out := new(MoveIPAddressAllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkResourceTransition) DeepCopyInto(out *NetworkResourceTransition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkResourceTransition.
func (in *NetworkResourceTransition) DeepCopy() *NetworkResourceTransition {
	if in == nil {
		return nil
	}
	out := new(NetworkResourceTransition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkResourceTransition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkResourceTransitionList) DeepCopyInto(out *NetworkResourceTransitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkResourceTransition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkResourceTransitionList.
func (in *NetworkResourceTransitionList) DeepCopy() *NetworkResourceTransitionList {
	if in == nil {
		return nil
	}
	out := new(NetworkResourceTransitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkResourceTransitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkResourceTransitionSpec) DeepCopyInto(out *NetworkResourceTransitionSpec) {
	*out = *in
	if in.CreateSubnetPort != nil {
		in, out := &in.CreateSubnetPort, &out.CreateSubnetPort
		*out = make([]CreateSubnetPortSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MoveIPAddressAllocation != nil {
		in, out := &in.MoveIPAddressAllocation, &out.MoveIPAddressAllocation
		*out = make([]MoveIPAddressAllocationSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkResourceTransitionSpec.
func (in *NetworkResourceTransitionSpec) DeepCopy() *NetworkResourceTransitionSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkResourceTransitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkResourceTransitionStatus) DeepCopyInto(out *NetworkResourceTransitionStatus) {
	*out = *in
	if in.CreateSubnetPort != nil {
		in, out := &in.CreateSubnetPort, &out.CreateSubnetPort
		*out = make([]CreateSubnetPortStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MoveIPAddressAllocation != nil {
		in, out := &in.MoveIPAddressAllocation, &out.MoveIPAddressAllocation
		*out = make([]MoveIPAddressAllocationStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkResourceTransitionStatus.
func (in *NetworkResourceTransitionStatus) DeepCopy() *NetworkResourceTransitionStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkResourceTransitionStatus)
	in.DeepCopyInto(out)
	return out
}
