// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/orgs/projects (interfaces: DnsRecordsClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDnsRecordsClient is a mock of DnsRecordsClient interface.
type MockDnsRecordsClient struct {
	ctrl     *gomock.Controller
	recorder *MockDnsRecordsClientMockRecorder
}

// MockDnsRecordsClientMockRecorder is the mock recorder for MockDnsRecordsClient.
type MockDnsRecordsClientMockRecorder struct {
	mock *MockDnsRecordsClient
}

// NewMockDnsRecordsClient creates a new mock instance.
func NewMockDnsRecordsClient(ctrl *gomock.Controller) *MockDnsRecordsClient {
	mock := &MockDnsRecordsClient{ctrl: ctrl}
	mock.recorder = &MockDnsRecordsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDnsRecordsClient) EXPECT() *MockDnsRecordsClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDnsRecordsClient) Delete(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDnsRecordsClientMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDnsRecordsClient)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockDnsRecordsClient) Get(arg0, arg1, arg2 string) (model.DnsRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.DnsRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDnsRecordsClientMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDnsRecordsClient)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockDnsRecordsClient) List(arg0, arg1 string, arg2 *string, arg3 *bool, arg4 *string, arg5 *int64, arg6 *bool, arg7, arg8 *string) (model.DnsRecordListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	ret0, _ := ret[0].(model.DnsRecordListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDnsRecordsClientMockRecorder) List(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDnsRecordsClient)(nil).List), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
}

// Patch mocks base method.
func (m *MockDnsRecordsClient) Patch(arg0, arg1, arg2 string, arg3 model.DnsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockDnsRecordsClientMockRecorder) Patch(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockDnsRecordsClient)(nil).Patch), arg0, arg1, arg2, arg3)
}

// Update mocks base method.
func (m *MockDnsRecordsClient) Update(arg0, arg1, arg2 string, arg3 model.DnsRecord) (model.DnsRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(model.DnsRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDnsRecordsClientMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDnsRecordsClient)(nil).Update), arg0, arg1, arg2, arg3)
}
