/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AddressBindingLister helps list AddressBindings.
// All objects returned here must be treated as read-only.
type AddressBindingLister interface {
	// List lists all AddressBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AddressBinding, err error)
	// AddressBindings returns an object that can list and get AddressBindings.
	AddressBindings(namespace string) AddressBindingNamespaceLister
	AddressBindingListerExpansion
}

// addressBindingLister implements the AddressBindingLister interface.
type addressBindingLister struct {
	indexer cache.Indexer
}

// NewAddressBindingLister returns a new AddressBindingLister.
func NewAddressBindingLister(indexer cache.Indexer) AddressBindingLister {
	return &addressBindingLister{indexer: indexer}
}

// List lists all AddressBindings in the indexer.
func (s *addressBindingLister) List(selector labels.Selector) (ret []*v1alpha1.AddressBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AddressBinding))
	})
	return ret, err
}

// AddressBindings returns an object that can list and get AddressBindings.
func (s *addressBindingLister) AddressBindings(namespace string) AddressBindingNamespaceLister {
	return addressBindingNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AddressBindingNamespaceLister helps list and get AddressBindings.
// All objects returned here must be treated as read-only.
type AddressBindingNamespaceLister interface {
	// List lists all AddressBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AddressBinding, err error)
	// Get retrieves the AddressBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.AddressBinding, error)
	AddressBindingNamespaceListerExpansion
}

// addressBindingNamespaceLister implements the AddressBindingNamespaceLister
// interface.
type addressBindingNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AddressBindings in the indexer for a given namespace.
func (s addressBindingNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.AddressBinding, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AddressBinding))
	})
	return ret, err
}

// Get retrieves the AddressBinding from the indexer for a given namespace and name.
func (s addressBindingNamespaceLister) Get(name string) (*v1alpha1.AddressBinding, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("addressbinding"), name)
	}
	return obj.(*v1alpha1.AddressBinding), nil
}
