/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPAddressAllocationLister helps list IPAddressAllocations.
// All objects returned here must be treated as read-only.
type IPAddressAllocationLister interface {
	// List lists all IPAddressAllocations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.IPAddressAllocation, err error)
	// IPAddressAllocations returns an object that can list and get IPAddressAllocations.
	IPAddressAllocations(namespace string) IPAddressAllocationNamespaceLister
	IPAddressAllocationListerExpansion
}

// iPAddressAllocationLister implements the IPAddressAllocationLister interface.
type iPAddressAllocationLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.IPAddressAllocation]
}

// NewIPAddressAllocationLister returns a new IPAddressAllocationLister.
func NewIPAddressAllocationLister(indexer cache.Indexer) IPAddressAllocationLister {
	return &iPAddressAllocationLister{listers.New[*vpcv1alpha1.IPAddressAllocation](indexer, vpcv1alpha1.Resource("ipaddressallocation"))}
}

// IPAddressAllocations returns an object that can list and get IPAddressAllocations.
func (s *iPAddressAllocationLister) IPAddressAllocations(namespace string) IPAddressAllocationNamespaceLister {
	return iPAddressAllocationNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.IPAddressAllocation](s.ResourceIndexer, namespace)}
}

// IPAddressAllocationNamespaceLister helps list and get IPAddressAllocations.
// All objects returned here must be treated as read-only.
type IPAddressAllocationNamespaceLister interface {
	// List lists all IPAddressAllocations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.IPAddressAllocation, err error)
	// Get retrieves the IPAddressAllocation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.IPAddressAllocation, error)
	IPAddressAllocationNamespaceListerExpansion
}

// iPAddressAllocationNamespaceLister implements the IPAddressAllocationNamespaceLister
// interface.
type iPAddressAllocationNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.IPAddressAllocation]
}
