/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPBlocksInfoLister helps list IPBlocksInfos.
// All objects returned here must be treated as read-only.
type IPBlocksInfoLister interface {
	// List lists all IPBlocksInfos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.IPBlocksInfo, err error)
	// Get retrieves the IPBlocksInfo from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.IPBlocksInfo, error)
	IPBlocksInfoListerExpansion
}

// iPBlocksInfoLister implements the IPBlocksInfoLister interface.
type iPBlocksInfoLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.IPBlocksInfo]
}

// NewIPBlocksInfoLister returns a new IPBlocksInfoLister.
func NewIPBlocksInfoLister(indexer cache.Indexer) IPBlocksInfoLister {
	return &iPBlocksInfoLister{listers.New[*vpcv1alpha1.IPBlocksInfo](indexer, vpcv1alpha1.Resource("ipblocksinfo"))}
}
