/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkInfoLister helps list NetworkInfos.
// All objects returned here must be treated as read-only.
type NetworkInfoLister interface {
	// List lists all NetworkInfos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.NetworkInfo, err error)
	// NetworkInfos returns an object that can list and get NetworkInfos.
	NetworkInfos(namespace string) NetworkInfoNamespaceLister
	NetworkInfoListerExpansion
}

// networkInfoLister implements the NetworkInfoLister interface.
type networkInfoLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.NetworkInfo]
}

// NewNetworkInfoLister returns a new NetworkInfoLister.
func NewNetworkInfoLister(indexer cache.Indexer) NetworkInfoLister {
	return &networkInfoLister{listers.New[*vpcv1alpha1.NetworkInfo](indexer, vpcv1alpha1.Resource("networkinfo"))}
}

// NetworkInfos returns an object that can list and get NetworkInfos.
func (s *networkInfoLister) NetworkInfos(namespace string) NetworkInfoNamespaceLister {
	return networkInfoNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.NetworkInfo](s.ResourceIndexer, namespace)}
}

// NetworkInfoNamespaceLister helps list and get NetworkInfos.
// All objects returned here must be treated as read-only.
type NetworkInfoNamespaceLister interface {
	// List lists all NetworkInfos in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.NetworkInfo, err error)
	// Get retrieves the NetworkInfo from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.NetworkInfo, error)
	NetworkInfoNamespaceListerExpansion
}

// networkInfoNamespaceLister implements the NetworkInfoNamespaceLister
// interface.
type networkInfoNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.NetworkInfo]
}
