/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceEndpointLister helps list ServiceEndpoints.
// All objects returned here must be treated as read-only.
type ServiceEndpointLister interface {
	// List lists all ServiceEndpoints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.ServiceEndpoint, err error)
	// ServiceEndpoints returns an object that can list and get ServiceEndpoints.
	ServiceEndpoints(namespace string) ServiceEndpointNamespaceLister
	ServiceEndpointListerExpansion
}

// serviceEndpointLister implements the ServiceEndpointLister interface.
type serviceEndpointLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.ServiceEndpoint]
}

// NewServiceEndpointLister returns a new ServiceEndpointLister.
func NewServiceEndpointLister(indexer cache.Indexer) ServiceEndpointLister {
	return &serviceEndpointLister{listers.New[*vpcv1alpha1.ServiceEndpoint](indexer, vpcv1alpha1.Resource("serviceendpoint"))}
}

// ServiceEndpoints returns an object that can list and get ServiceEndpoints.
func (s *serviceEndpointLister) ServiceEndpoints(namespace string) ServiceEndpointNamespaceLister {
	return serviceEndpointNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.ServiceEndpoint](s.ResourceIndexer, namespace)}
}

// ServiceEndpointNamespaceLister helps list and get ServiceEndpoints.
// All objects returned here must be treated as read-only.
type ServiceEndpointNamespaceLister interface {
	// List lists all ServiceEndpoints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.ServiceEndpoint, err error)
	// Get retrieves the ServiceEndpoint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.ServiceEndpoint, error)
	ServiceEndpointNamespaceListerExpansion
}

// serviceEndpointNamespaceLister implements the ServiceEndpointNamespaceLister
// interface.
type serviceEndpointNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.ServiceEndpoint]
}
