/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// StaticRouteLister helps list StaticRoutes.
// All objects returned here must be treated as read-only.
type StaticRouteLister interface {
	// List lists all StaticRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.StaticRoute, err error)
	// StaticRoutes returns an object that can list and get StaticRoutes.
	StaticRoutes(namespace string) StaticRouteNamespaceLister
	StaticRouteListerExpansion
}

// staticRouteLister implements the StaticRouteLister interface.
type staticRouteLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.StaticRoute]
}

// NewStaticRouteLister returns a new StaticRouteLister.
func NewStaticRouteLister(indexer cache.Indexer) StaticRouteLister {
	return &staticRouteLister{listers.New[*vpcv1alpha1.StaticRoute](indexer, vpcv1alpha1.Resource("staticroute"))}
}

// StaticRoutes returns an object that can list and get StaticRoutes.
func (s *staticRouteLister) StaticRoutes(namespace string) StaticRouteNamespaceLister {
	return staticRouteNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.StaticRoute](s.ResourceIndexer, namespace)}
}

// StaticRouteNamespaceLister helps list and get StaticRoutes.
// All objects returned here must be treated as read-only.
type StaticRouteNamespaceLister interface {
	// List lists all StaticRoutes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.StaticRoute, err error)
	// Get retrieves the StaticRoute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.StaticRoute, error)
	StaticRouteNamespaceListerExpansion
}

// staticRouteNamespaceLister implements the StaticRouteNamespaceLister
// interface.
type staticRouteNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.StaticRoute]
}
