/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SubnetConnectionBindingMapLister helps list SubnetConnectionBindingMaps.
// All objects returned here must be treated as read-only.
type SubnetConnectionBindingMapLister interface {
	// List lists all SubnetConnectionBindingMaps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetConnectionBindingMap, err error)
	// SubnetConnectionBindingMaps returns an object that can list and get SubnetConnectionBindingMaps.
	SubnetConnectionBindingMaps(namespace string) SubnetConnectionBindingMapNamespaceLister
	SubnetConnectionBindingMapListerExpansion
}

// subnetConnectionBindingMapLister implements the SubnetConnectionBindingMapLister interface.
type subnetConnectionBindingMapLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetConnectionBindingMap]
}

// NewSubnetConnectionBindingMapLister returns a new SubnetConnectionBindingMapLister.
func NewSubnetConnectionBindingMapLister(indexer cache.Indexer) SubnetConnectionBindingMapLister {
	return &subnetConnectionBindingMapLister{listers.New[*vpcv1alpha1.SubnetConnectionBindingMap](indexer, vpcv1alpha1.Resource("subnetconnectionbindingmap"))}
}

// SubnetConnectionBindingMaps returns an object that can list and get SubnetConnectionBindingMaps.
func (s *subnetConnectionBindingMapLister) SubnetConnectionBindingMaps(namespace string) SubnetConnectionBindingMapNamespaceLister {
	return subnetConnectionBindingMapNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.SubnetConnectionBindingMap](s.ResourceIndexer, namespace)}
}

// SubnetConnectionBindingMapNamespaceLister helps list and get SubnetConnectionBindingMaps.
// All objects returned here must be treated as read-only.
type SubnetConnectionBindingMapNamespaceLister interface {
	// List lists all SubnetConnectionBindingMaps in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetConnectionBindingMap, err error)
	// Get retrieves the SubnetConnectionBindingMap from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.SubnetConnectionBindingMap, error)
	SubnetConnectionBindingMapNamespaceListerExpansion
}

// subnetConnectionBindingMapNamespaceLister implements the SubnetConnectionBindingMapNamespaceLister
// interface.
type subnetConnectionBindingMapNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetConnectionBindingMap]
}
