/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SubnetIPReservationLister helps list SubnetIPReservations.
// All objects returned here must be treated as read-only.
type SubnetIPReservationLister interface {
	// List lists all SubnetIPReservations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetIPReservation, err error)
	// SubnetIPReservations returns an object that can list and get SubnetIPReservations.
	SubnetIPReservations(namespace string) SubnetIPReservationNamespaceLister
	SubnetIPReservationListerExpansion
}

// subnetIPReservationLister implements the SubnetIPReservationLister interface.
type subnetIPReservationLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetIPReservation]
}

// NewSubnetIPReservationLister returns a new SubnetIPReservationLister.
func NewSubnetIPReservationLister(indexer cache.Indexer) SubnetIPReservationLister {
	return &subnetIPReservationLister{listers.New[*vpcv1alpha1.SubnetIPReservation](indexer, vpcv1alpha1.Resource("subnetipreservation"))}
}

// SubnetIPReservations returns an object that can list and get SubnetIPReservations.
func (s *subnetIPReservationLister) SubnetIPReservations(namespace string) SubnetIPReservationNamespaceLister {
	return subnetIPReservationNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.SubnetIPReservation](s.ResourceIndexer, namespace)}
}

// SubnetIPReservationNamespaceLister helps list and get SubnetIPReservations.
// All objects returned here must be treated as read-only.
type SubnetIPReservationNamespaceLister interface {
	// List lists all SubnetIPReservations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetIPReservation, err error)
	// Get retrieves the SubnetIPReservation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.SubnetIPReservation, error)
	SubnetIPReservationNamespaceListerExpansion
}

// subnetIPReservationNamespaceLister implements the SubnetIPReservationNamespaceLister
// interface.
type subnetIPReservationNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetIPReservation]
}
