/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SubnetPortSettingLister helps list SubnetPortSettings.
// All objects returned here must be treated as read-only.
type SubnetPortSettingLister interface {
	// List lists all SubnetPortSettings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetPortSetting, err error)
	// SubnetPortSettings returns an object that can list and get SubnetPortSettings.
	SubnetPortSettings(namespace string) SubnetPortSettingNamespaceLister
	SubnetPortSettingListerExpansion
}

// subnetPortSettingLister implements the SubnetPortSettingLister interface.
type subnetPortSettingLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetPortSetting]
}

// NewSubnetPortSettingLister returns a new SubnetPortSettingLister.
func NewSubnetPortSettingLister(indexer cache.Indexer) SubnetPortSettingLister {
	return &subnetPortSettingLister{listers.New[*vpcv1alpha1.SubnetPortSetting](indexer, vpcv1alpha1.Resource("subnetportsetting"))}
}

// SubnetPortSettings returns an object that can list and get SubnetPortSettings.
func (s *subnetPortSettingLister) SubnetPortSettings(namespace string) SubnetPortSettingNamespaceLister {
	return subnetPortSettingNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.SubnetPortSetting](s.ResourceIndexer, namespace)}
}

// SubnetPortSettingNamespaceLister helps list and get SubnetPortSettings.
// All objects returned here must be treated as read-only.
type SubnetPortSettingNamespaceLister interface {
	// List lists all SubnetPortSettings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetPortSetting, err error)
	// Get retrieves the SubnetPortSetting from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.SubnetPortSetting, error)
	SubnetPortSettingNamespaceListerExpansion
}

// subnetPortSettingNamespaceLister implements the SubnetPortSettingNamespaceLister
// interface.
type subnetPortSettingNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetPortSetting]
}
