/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SubnetSetLister helps list SubnetSets.
// All objects returned here must be treated as read-only.
type SubnetSetLister interface {
	// List lists all SubnetSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetSet, err error)
	// SubnetSets returns an object that can list and get SubnetSets.
	SubnetSets(namespace string) SubnetSetNamespaceLister
	SubnetSetListerExpansion
}

// subnetSetLister implements the SubnetSetLister interface.
type subnetSetLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetSet]
}

// NewSubnetSetLister returns a new SubnetSetLister.
func NewSubnetSetLister(indexer cache.Indexer) SubnetSetLister {
	return &subnetSetLister{listers.New[*vpcv1alpha1.SubnetSet](indexer, vpcv1alpha1.Resource("subnetset"))}
}

// SubnetSets returns an object that can list and get SubnetSets.
func (s *subnetSetLister) SubnetSets(namespace string) SubnetSetNamespaceLister {
	return subnetSetNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.SubnetSet](s.ResourceIndexer, namespace)}
}

// SubnetSetNamespaceLister helps list and get SubnetSets.
// All objects returned here must be treated as read-only.
type SubnetSetNamespaceLister interface {
	// List lists all SubnetSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetSet, err error)
	// Get retrieves the SubnetSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.SubnetSet, error)
	SubnetSetNamespaceListerExpansion
}

// subnetSetNamespaceLister implements the SubnetSetNamespaceLister
// interface.
type subnetSetNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetSet]
}
