/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SubnetPortLister helps list SubnetPorts.
// All objects returned here must be treated as read-only.
type SubnetPortLister interface {
	// List lists all SubnetPorts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetPort, err error)
	// SubnetPorts returns an object that can list and get SubnetPorts.
	SubnetPorts(namespace string) SubnetPortNamespaceLister
	SubnetPortListerExpansion
}

// subnetPortLister implements the SubnetPortLister interface.
type subnetPortLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetPort]
}

// NewSubnetPortLister returns a new SubnetPortLister.
func NewSubnetPortLister(indexer cache.Indexer) SubnetPortLister {
	return &subnetPortLister{listers.New[*vpcv1alpha1.SubnetPort](indexer, vpcv1alpha1.Resource("subnetport"))}
}

// SubnetPorts returns an object that can list and get SubnetPorts.
func (s *subnetPortLister) SubnetPorts(namespace string) SubnetPortNamespaceLister {
	return subnetPortNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.SubnetPort](s.ResourceIndexer, namespace)}
}

// SubnetPortNamespaceLister helps list and get SubnetPorts.
// All objects returned here must be treated as read-only.
type SubnetPortNamespaceLister interface {
	// List lists all SubnetPorts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.SubnetPort, err error)
	// Get retrieves the SubnetPort from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.SubnetPort, error)
	SubnetPortNamespaceListerExpansion
}

// subnetPortNamespaceLister implements the SubnetPortNamespaceLister
// interface.
type subnetPortNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.SubnetPort]
}
