/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VPCEndpointLister helps list VPCEndpoints.
// All objects returned here must be treated as read-only.
type VPCEndpointLister interface {
	// List lists all VPCEndpoints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.VPCEndpoint, err error)
	// VPCEndpoints returns an object that can list and get VPCEndpoints.
	VPCEndpoints(namespace string) VPCEndpointNamespaceLister
	VPCEndpointListerExpansion
}

// vPCEndpointLister implements the VPCEndpointLister interface.
type vPCEndpointLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.VPCEndpoint]
}

// NewVPCEndpointLister returns a new VPCEndpointLister.
func NewVPCEndpointLister(indexer cache.Indexer) VPCEndpointLister {
	return &vPCEndpointLister{listers.New[*vpcv1alpha1.VPCEndpoint](indexer, vpcv1alpha1.Resource("vpcendpoint"))}
}

// VPCEndpoints returns an object that can list and get VPCEndpoints.
func (s *vPCEndpointLister) VPCEndpoints(namespace string) VPCEndpointNamespaceLister {
	return vPCEndpointNamespaceLister{listers.NewNamespaced[*vpcv1alpha1.VPCEndpoint](s.ResourceIndexer, namespace)}
}

// VPCEndpointNamespaceLister helps list and get VPCEndpoints.
// All objects returned here must be treated as read-only.
type VPCEndpointNamespaceLister interface {
	// List lists all VPCEndpoints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.VPCEndpoint, err error)
	// Get retrieves the VPCEndpoint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.VPCEndpoint, error)
	VPCEndpointNamespaceListerExpansion
}

// vPCEndpointNamespaceLister implements the VPCEndpointNamespaceLister
// interface.
type vPCEndpointNamespaceLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.VPCEndpoint]
}
