/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VPCNetworkConfigurationLister helps list VPCNetworkConfigurations.
// All objects returned here must be treated as read-only.
type VPCNetworkConfigurationLister interface {
	// List lists all VPCNetworkConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vpcv1alpha1.VPCNetworkConfiguration, err error)
	// Get retrieves the VPCNetworkConfiguration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vpcv1alpha1.VPCNetworkConfiguration, error)
	VPCNetworkConfigurationListerExpansion
}

// vPCNetworkConfigurationLister implements the VPCNetworkConfigurationLister interface.
type vPCNetworkConfigurationLister struct {
	listers.ResourceIndexer[*vpcv1alpha1.VPCNetworkConfiguration]
}

// NewVPCNetworkConfigurationLister returns a new VPCNetworkConfigurationLister.
func NewVPCNetworkConfigurationLister(indexer cache.Indexer) VPCNetworkConfigurationLister {
	return &vPCNetworkConfigurationLister{listers.New[*vpcv1alpha1.VPCNetworkConfiguration](indexer, vpcv1alpha1.Resource("vpcnetworkconfiguration"))}
}
