package subnetbinding

import (
	"context"
	"fmt"
	"sync"

	"github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/client-go/util/retry"

	"github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	"github.com/vmware-tanzu/nsx-operator/pkg/logger"
	servicecommon "github.com/vmware-tanzu/nsx-operator/pkg/nsx/services/common"
	nsxutil "github.com/vmware-tanzu/nsx-operator/pkg/nsx/util"
	"github.com/vmware-tanzu/nsx-operator/pkg/util"
)

var (
	log                                    = logger.Log
	ResourceTypeSubnetConnectionBindingMap = servicecommon.ResourceTypeSubnetConnectionBindingMap
	enforceRevisionCheckParam              = false
	markedForDelete                        = true
)

type BindingService struct {
	builder *servicecommon.PolicyTreeBuilder[*model.SubnetConnectionBindingMap]
	servicecommon.Service
	BindingStore *BindingStore
}

// InitializeService initializes SubnetConnectionBindingMap service.
func InitializeService(service servicecommon.Service) (*BindingService, error) {
	builder, _ := servicecommon.PolicyPathVpcSubnetConnectionBindingMap.NewPolicyTreeBuilder()
	wg := sync.WaitGroup{}
	fatalErrors := make(chan error, 1)

	bindingService := &BindingService{
		Service:      service,
		BindingStore: SetupStore(),
		builder:      builder,
	}

	wg.Add(1)
	go service.InitializeResourceStore(&wg, fatalErrors, ResourceTypeSubnetConnectionBindingMap, nil, bindingService.BindingStore)
	wg.Wait()

	if len(fatalErrors) > 0 {
		err := <-fatalErrors
		return bindingService, err
	}

	return bindingService, nil
}

// CreateOrUpdateSubnetConnectionBindingMap creates or updates the SubnetConnectionBindingMaps with the given
// SubnetConnectionBindingMap CR and attaches it to the parentSubnets.
func (s *BindingService) CreateOrUpdateSubnetConnectionBindingMap(
	subnetBinding *v1alpha1.SubnetConnectionBindingMap,
	vlanID int64,
	childSubnetPath string,
	parentSubnetPaths []string) error {
	desiredBMmap := bindingMapsToMap(s.buildSubnetBindings(subnetBinding, vlanID, parentSubnetPaths))
	existingBMmap := bindingMapsToMap(s.BindingStore.getBindingsByBindingMapCRUID(string(subnetBinding.UID)))
	updatedBindingMaps := make([]*model.SubnetConnectionBindingMap, 0)
	for k, v := range desiredBMmap {
		existBindingMap, found := existingBMmap[k]
		if !found {
			updatedBindingMaps = append(updatedBindingMaps, v)
			continue
		}
		// Update NSX SubnetConnectionBindingMap's id and display_name with the existing settings.
		v.Id = String(*existBindingMap.Id)
		v.DisplayName = String(*existBindingMap.DisplayName)
		changed := servicecommon.CompareResource(SubnetConnectionBindingMapToComparable(existBindingMap), SubnetConnectionBindingMapToComparable(v))
		if changed {
			updatedBindingMaps = append(updatedBindingMaps, v)
		}
	}
	// Mark the SubnetConnectionBindingMap as for-delete if it exists in the store but does not exist in the desired resources.
	for k, v := range existingBMmap {
		_, found := desiredBMmap[k]
		if !found {
			toDelBindingMap := *v
			toDelBindingMap.MarkedForDelete = Bool(true)
			updatedBindingMaps = append(updatedBindingMaps, &toDelBindingMap)
		}
	}

	if err := s.Apply(childSubnetPath, updatedBindingMaps); err != nil {
		return err
	}

	return nil
}

// DeleteSubnetConnectionBindingMapsByCRName deletes all the SubnetConnectionBindingMaps generated by the given subnetBinding
// CR's Name.
func (s *BindingService) DeleteSubnetConnectionBindingMapsByCRName(bindingName string, bindingNamespace string) error {
	bindingMaps := s.BindingStore.getBindingsByBindingMapCRName(bindingName, bindingNamespace)
	return s.deleteSubnetConnectionBindingMaps(bindingMaps)
}

// DeleteSubnetConnectionBindingMapsByParentSubnet deletes all the SubnetConnectionBindingMaps bound to the
// given parentSubnet.
func (s *BindingService) DeleteSubnetConnectionBindingMapsByParentSubnet(parentSubnet *model.VpcSubnet) error {
	bindingMaps := make([]*model.SubnetConnectionBindingMap, 0)
	// This should not happen in the production setup, adding this check is for security.
	if parentSubnet.Path == nil {
		log.Info("Parent VpcSubnet had no configured Path, ignoring", "subnet", *parentSubnet.Id)
		return nil
	}
	subnetPath := *parentSubnet.Path
	bindingMaps = append(bindingMaps, s.BindingStore.getBindingsByParentSubnet(subnetPath)...)
	return s.deleteSubnetConnectionBindingMaps(bindingMaps)
}

// GetSubnetConnectionBindingMapsBySubnet returns all the SubnetConnectionBindingMaps referred to the given subnet.
// The function returns the SubnetConnectionBindingMaps associated with the subnet if exists, otherwise it returns
// the SubnetConnectionBindingMaps connected to the subnet.
func (s *BindingService) GetSubnetConnectionBindingMapsBySubnet(subnet *model.VpcSubnet) []*model.SubnetConnectionBindingMap {
	bindingMapsByChild := s.GetSubnetConnectionBindingMapsByChildSubnet(*subnet.Path)
	if len(bindingMapsByChild) > 0 {
		return bindingMapsByChild
	}
	return s.GetSubnetConnectionBindingMapsByParentSubnet(*subnet.Path)
}

// GetSubnetConnectionBindingMapsByChildSubnet returns the SubnetConnectionBindingMaps associated with the subnet.
func (s *BindingService) GetSubnetConnectionBindingMapsByChildSubnet(subnetPath string) []*model.SubnetConnectionBindingMap {
	return s.BindingStore.getBindingsByChildSubnet(subnetPath)
}

// GetSubnetConnectionBindingMapsByParentSubnet returns the SubnetConnectionBindingMaps connected to the subnet.
func (s *BindingService) GetSubnetConnectionBindingMapsByParentSubnet(subnetPath string) []*model.SubnetConnectionBindingMap {
	return s.BindingStore.getBindingsByParentSubnet(subnetPath)
}

func (s *BindingService) GetSubnetConnectionBindingMapCRsBySubnet(subnet *model.VpcSubnet) []*v1alpha1.SubnetConnectionBindingMap {
	nsxBindingMaps := s.GetSubnetConnectionBindingMapsBySubnet(subnet)
	if len(nsxBindingMaps) == 0 {
		return nil
	}

	subnetConnectionBindingMaps := sets.New[*v1alpha1.SubnetConnectionBindingMap]()
	for _, bm := range nsxBindingMaps {
		obj, err := buildSubnetConnectionBindingMapCR(bm)
		if err != nil {
			log.Error(err, "Unable to get SubnetConnectionBindingMap CR from NSX resource", "SubnetConnectionBindingMap", *bm.Id)
			continue
		}
		subnetConnectionBindingMaps.Insert(obj)
	}
	return subnetConnectionBindingMaps.UnsortedList()
}

func (s *BindingService) ListSubnetConnectionBindingMapCRUIDsInStore() sets.Set[string] {
	crUIDs := sets.New[string]()
	for _, obj := range s.BindingStore.List() {
		bm, _ := obj.(*model.SubnetConnectionBindingMap)
		res, err := buildSubnetConnectionBindingMapCR(bm)
		if err != nil {
			log.Error(err, "Unable to get SubnetConnectionBindingMap CR from NSX resource", "bindingMap", *bm.Id)
			continue
		}
		crUIDs.Insert(string(res.UID))
	}
	return crUIDs
}

// Apply sync bindingMaps on NSX and save into the store if succeeded to realize.
func (s *BindingService) Apply(subnetPath string, bindingMaps []*model.SubnetConnectionBindingMap) error {
	vpcInfo, err := servicecommon.ParseVPCResourcePath(subnetPath)
	if err != nil {
		return err
	}
	subnetID := vpcInfo.ID
	orgRoot, err := s.builder.BuildOrgRoot(bindingMaps, subnetPath)
	if err != nil {
		return err
	}

	if err = s.NSXClient.OrgRootClient.Patch(*orgRoot, &enforceRevisionCheckParam); err != nil {
		log.Error(err, "Failed to patch SubnetConnectionBindingMaps on NSX", "orgID", vpcInfo.OrgID, "projectID", vpcInfo.ProjectID, "vpcID", vpcInfo.VPCID, "subnetID", subnetID, "subnetConnectionBindingMaps", bindingMaps)
		err = nsxutil.TransNSXApiError(err)
		return err
	}

	// No need to check the deleted bindingmaps from NSX, delete them from store directly.
	var pendingBindingMaps []*model.SubnetConnectionBindingMap
	for i := range bindingMaps {
		bm := bindingMaps[i]
		if bm.MarkedForDelete != nil && *bm.MarkedForDelete {
			s.BindingStore.Apply(bm)
			continue
		}
		pendingBindingMaps = append(pendingBindingMaps, bm)
	}

	// In scaled case, when HAPI call succeeds, the SubnetConnectionBindingMaps may not be immediately available in NSX.
	// So we need to retry to list the SubnetConnectionBindingMaps from NSX until they are available.
	nsxBindingMaps := make(map[string]model.SubnetConnectionBindingMap)
	var cursor *string
	err = retry.OnError(util.NSXTRealizeRetry, func(err error) bool {
		if err == nil {
			return false
		}
		if _, ok := err.(*nsxutil.NSXApiError); ok {
			return false
		}
		return true
	}, func() error {
		for {
			subnetBindingListResult, listErr := s.NSXClient.SubnetConnectionBindingMapsClient.List(vpcInfo.OrgID, vpcInfo.ProjectID, vpcInfo.VPCID, subnetID, cursor, nil, nil, nil, nil, nil)
			if listErr != nil {
				log.Error(listErr, "Failed to list SubnetConnectionBindingMaps from NSX under Subnet", "orgID", vpcInfo.OrgID, "projectID", vpcInfo.ProjectID, "vpcID", vpcInfo.VPCID, "subnetID", subnetID, "subnetConnectionBindingMaps", pendingBindingMaps)
				return nsxutil.TransNSXApiError(listErr)
			}
			for _, bm := range subnetBindingListResult.Results {
				nsxBindingMaps[*bm.Id] = bm
			}
			if subnetBindingListResult.Cursor == nil {
				break
			}
			cursor = subnetBindingListResult.Cursor
		}
		var missingBindingMaps []*model.SubnetConnectionBindingMap
		for i := range pendingBindingMaps {
			bm := pendingBindingMaps[i]
			nsxBindingMap, ok := nsxBindingMaps[*bm.Id]
			if ok {
				s.BindingStore.Apply(&nsxBindingMap)
				continue
			}
			missingBindingMaps = append(missingBindingMaps, bm)
		}
		pendingBindingMaps = missingBindingMaps
		if len(missingBindingMaps) > 0 {
			err := fmt.Errorf("Subnet connection binding maps not found in NSX: %v", missingBindingMaps)
			log.Error(err, "Missing SubnetConnectionBindingMaps in NSX, will retry")
			return err
		}
		return nil
	})
	return err
}

// deleteSubnetConnectionBindingMaps uses HAPI call to delete multiple SubnetConnectionBindingMaps on NSX in one
// transaction, and then delete these resources from local store. Since NSX can accept no more than 5K children Nodes
// in one HAPI call, paging is used in this function to avoid scale issues.
func (s *BindingService) deleteSubnetConnectionBindingMaps(bindingMaps []*model.SubnetConnectionBindingMap) error {
	// Add this check for security purpose. The caller has similar pre-check and returned if no items exist in the bindingMaps.
	bindingMapsCount := len(bindingMaps)
	if bindingMapsCount == 0 {
		log.Info("No existing SubnetConnectionBindingMaps found in the store")
		return nil
	}
	markForDelete := true
	for _, bm := range bindingMaps {
		bm.MarkedForDelete = &markForDelete
	}

	return s.builder.PagingUpdateResources(context.TODO(), bindingMaps, servicecommon.DefaultHAPIChildrenCount, s.NSXClient, func(deletedObjs []*model.SubnetConnectionBindingMap) {
		s.BindingStore.DeleteMultipleObjects(deletedObjs)
	})
}

func (s *BindingService) DeleteMultiSubnetConnectionBindingMapsByCRs(bindingCRs sets.Set[string]) error {
	if bindingCRs.Len() == 0 {
		return nil
	}
	finalBindingMaps := make([]*model.SubnetConnectionBindingMap, 0)
	for crID := range bindingCRs {
		bms := s.BindingStore.getBindingsByBindingMapCRUID(crID)
		finalBindingMaps = append(finalBindingMaps, bms...)
	}
	return s.deleteSubnetConnectionBindingMaps(finalBindingMaps)
}

func (s *BindingService) GetSubnetConnectionBindingMapCRName(bindingMap *model.SubnetConnectionBindingMap) string {
	if bindingMap == nil {
		return ""
	}
	for _, tag := range bindingMap.Tags {
		if *tag.Scope == servicecommon.TagScopeSubnetBindingCRName {
			return *tag.Tag
		}
	}
	return ""
}

// bindingMapsToMap converts a slice of NSX SubnetConnectionBindingMaps to a map, the key is the parent VpcSubnetPath
// and the value is the SubnetConnectionBindingMap. Note, the caller should guarantee every SubnetConnectionBindingMap
// in the slice has a different parent NSX VpcSubnet.
func bindingMapsToMap(bindingMaps []*model.SubnetConnectionBindingMap) map[string]*model.SubnetConnectionBindingMap {
	bmMap := make(map[string]*model.SubnetConnectionBindingMap)
	for _, bm := range bindingMaps {
		bmMap[*bm.SubnetPath] = bm
	}
	return bmMap
}
