/* Copyright © 2023 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// IPPoolListerExpansion allows custom methods to be added to
// IPPoolLister.
type IPPoolListerExpansion interface{}

// IPPoolNamespaceListerExpansion allows custom methods to be added to
// IPPoolNamespaceLister.
type IPPoolNamespaceListerExpansion interface{}
