# permissions for end users to view securitypolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: securitypolicy-viewer-role
rules:
- apiGroups:
  - securitypolicy.github.com
  resources:
  - securitypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - securitypolicy.github.com
  resources:
  - securitypolicies/status
  verbs:
  - get
