// Code generated by hand to mirror MockGen output (mockgen v1.6 cannot parse generic sets.Set in interfaces).

package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/sets"

	dns "github.com/vmware-tanzu/nsx-operator/pkg/nsx/services/dns"
	extdns "github.com/vmware-tanzu/nsx-operator/pkg/third_party/externaldns/endpoint"
)

// MockDNSRecordProvider is a mock of dns.DNSRecordProvider.
type MockDNSRecordProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDNSRecordProviderMockRecorder
}

// MockDNSRecordProviderMockRecorder is the mock recorder for MockDNSRecordProvider.
type MockDNSRecordProviderMockRecorder struct {
	mock *MockDNSRecordProvider
}

// NewMockDNSRecordProvider creates a new mock instance.
func NewMockDNSRecordProvider(ctrl *gomock.Controller) *MockDNSRecordProvider {
	mock := &MockDNSRecordProvider{ctrl: ctrl}
	mock.recorder = &MockDNSRecordProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSRecordProvider) EXPECT() *MockDNSRecordProviderMockRecorder {
	return m.recorder
}

// CreateOrUpdateRecords mocks base method.
func (m *MockDNSRecordProvider) CreateOrUpdateRecords(ctx context.Context, batch *dns.AggregatedDNSEndpoints) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateRecords", ctx, batch)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateRecords indicates an expected call of CreateOrUpdateRecords.
func (mr *MockDNSRecordProviderMockRecorder) CreateOrUpdateRecords(ctx, batch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateRecords", reflect.TypeOf((*MockDNSRecordProvider)(nil).CreateOrUpdateRecords), ctx, batch)
}

// DeleteRecordByOwnerNN mocks base method.
func (m *MockDNSRecordProvider) DeleteRecordByOwnerNN(ctx context.Context, kind, namespace, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordByOwnerNN", ctx, kind, namespace, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecordByOwnerNN indicates an expected call of DeleteRecordByOwnerNN.
func (mr *MockDNSRecordProviderMockRecorder) DeleteRecordByOwnerNN(ctx, kind, namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordByOwnerNN", reflect.TypeOf((*MockDNSRecordProvider)(nil).DeleteRecordByOwnerNN), ctx, kind, namespace, name)
}

// ValidateEndpointsByZone mocks base method.
func (m *MockDNSRecordProvider) ValidateEndpointsByZone(namespace string, owner *dns.ResourceRef, eps []*extdns.Endpoint) ([]dns.EndpointRow, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEndpointsByZone", namespace, owner, eps)
	ret0, _ := ret[0].([]dns.EndpointRow)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateEndpointsByZone indicates an expected call of ValidateEndpointsByZone.
func (mr *MockDNSRecordProviderMockRecorder) ValidateEndpointsByZone(namespace, owner, eps interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEndpointsByZone", reflect.TypeOf((*MockDNSRecordProvider)(nil).ValidateEndpointsByZone), namespace, owner, eps)
}

// DeleteRecordsForOwnerOutsideAllowedZones mocks base method.
func (m *MockDNSRecordProvider) DeleteRecordsForOwnerOutsideAllowedZones(ctx context.Context, kind, namespace, name string, allowedZonePaths sets.Set[string]) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordsForOwnerOutsideAllowedZones", ctx, kind, namespace, name, allowedZonePaths)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRecordsForOwnerOutsideAllowedZones indicates an expected call of DeleteRecordsForOwnerOutsideAllowedZones.
func (mr *MockDNSRecordProviderMockRecorder) DeleteRecordsForOwnerOutsideAllowedZones(ctx, kind, namespace, name, allowedZonePaths interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordsForOwnerOutsideAllowedZones", reflect.TypeOf((*MockDNSRecordProvider)(nil).DeleteRecordsForOwnerOutsideAllowedZones), ctx, kind, namespace, name, allowedZonePaths)
}

// ListReferredGatewayNN mocks base method.
func (m *MockDNSRecordProvider) ListReferredGatewayNN() sets.Set[types.NamespacedName] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReferredGatewayNN")
	ret0, _ := ret[0].(sets.Set[types.NamespacedName])
	return ret0
}

// ListReferredGatewayNN indicates an expected call of ListReferredGatewayNN.
func (mr *MockDNSRecordProviderMockRecorder) ListReferredGatewayNN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReferredGatewayNN", reflect.TypeOf((*MockDNSRecordProvider)(nil).ListReferredGatewayNN))
}

// ListRecordOwnerResource mocks base method.
func (m *MockDNSRecordProvider) ListRecordOwnerResource() map[string]sets.Set[types.NamespacedName] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordOwnerResource")
	ret0, _ := ret[0].(map[string]sets.Set[types.NamespacedName])
	return ret0
}

// ListRecordOwnerResource indicates an expected call of ListRecordOwnerResource.
func (mr *MockDNSRecordProviderMockRecorder) ListRecordOwnerResource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordOwnerResource", reflect.TypeOf((*MockDNSRecordProvider)(nil).ListRecordOwnerResource))
}
