/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AddressBindingListerExpansion allows custom methods to be added to
// AddressBindingLister.
type AddressBindingListerExpansion interface{}

// AddressBindingNamespaceListerExpansion allows custom methods to be added to
// AddressBindingNamespaceLister.
type AddressBindingNamespaceListerExpansion interface{}

// IPAddressAllocationListerExpansion allows custom methods to be added to
// IPAddressAllocationLister.
type IPAddressAllocationListerExpansion interface{}

// IPAddressAllocationNamespaceListerExpansion allows custom methods to be added to
// IPAddressAllocationNamespaceLister.
type IPAddressAllocationNamespaceListerExpansion interface{}

// IPBlocksInfoListerExpansion allows custom methods to be added to
// IPBlocksInfoLister.
type IPBlocksInfoListerExpansion interface{}

// IPBlocksInfoNamespaceListerExpansion allows custom methods to be added to
// IPBlocksInfoNamespaceLister.
type IPBlocksInfoNamespaceListerExpansion interface{}

// NetworkInfoListerExpansion allows custom methods to be added to
// NetworkInfoLister.
type NetworkInfoListerExpansion interface{}

// NetworkInfoNamespaceListerExpansion allows custom methods to be added to
// NetworkInfoNamespaceLister.
type NetworkInfoNamespaceListerExpansion interface{}

// SecurityPolicyListerExpansion allows custom methods to be added to
// SecurityPolicyLister.
type SecurityPolicyListerExpansion interface{}

// SecurityPolicyNamespaceListerExpansion allows custom methods to be added to
// SecurityPolicyNamespaceLister.
type SecurityPolicyNamespaceListerExpansion interface{}

// StaticRouteListerExpansion allows custom methods to be added to
// StaticRouteLister.
type StaticRouteListerExpansion interface{}

// StaticRouteNamespaceListerExpansion allows custom methods to be added to
// StaticRouteNamespaceLister.
type StaticRouteNamespaceListerExpansion interface{}

// SubnetListerExpansion allows custom methods to be added to
// SubnetLister.
type SubnetListerExpansion interface{}

// SubnetNamespaceListerExpansion allows custom methods to be added to
// SubnetNamespaceLister.
type SubnetNamespaceListerExpansion interface{}

// SubnetPortListerExpansion allows custom methods to be added to
// SubnetPortLister.
type SubnetPortListerExpansion interface{}

// SubnetPortNamespaceListerExpansion allows custom methods to be added to
// SubnetPortNamespaceLister.
type SubnetPortNamespaceListerExpansion interface{}

// SubnetSetListerExpansion allows custom methods to be added to
// SubnetSetLister.
type SubnetSetListerExpansion interface{}

// SubnetSetNamespaceListerExpansion allows custom methods to be added to
// SubnetSetNamespaceLister.
type SubnetSetNamespaceListerExpansion interface{}

// VPCNetworkConfigurationListerExpansion allows custom methods to be added to
// VPCNetworkConfigurationLister.
type VPCNetworkConfigurationListerExpansion interface{}
