/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AddressBindingsGetter has a method to return a AddressBindingInterface.
// A group's client should implement this interface.
type AddressBindingsGetter interface {
	AddressBindings(namespace string) AddressBindingInterface
}

// AddressBindingInterface has methods to work with AddressBinding resources.
type AddressBindingInterface interface {
	Create(ctx context.Context, addressBinding *vpcv1alpha1.AddressBinding, opts v1.CreateOptions) (*vpcv1alpha1.AddressBinding, error)
	Update(ctx context.Context, addressBinding *vpcv1alpha1.AddressBinding, opts v1.UpdateOptions) (*vpcv1alpha1.AddressBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, addressBinding *vpcv1alpha1.AddressBinding, opts v1.UpdateOptions) (*vpcv1alpha1.AddressBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.AddressBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.AddressBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.AddressBinding, err error)
	AddressBindingExpansion
}

// addressBindings implements AddressBindingInterface
type addressBindings struct {
	*gentype.ClientWithList[*vpcv1alpha1.AddressBinding, *vpcv1alpha1.AddressBindingList]
}

// newAddressBindings returns a AddressBindings
func newAddressBindings(c *CrdV1alpha1Client, namespace string) *addressBindings {
	return &addressBindings{
		gentype.NewClientWithList[*vpcv1alpha1.AddressBinding, *vpcv1alpha1.AddressBindingList](
			"addressbindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.AddressBinding { return &vpcv1alpha1.AddressBinding{} },
			func() *vpcv1alpha1.AddressBindingList { return &vpcv1alpha1.AddressBindingList{} },
		),
	}
}
