/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPAddressAllocationsGetter has a method to return a IPAddressAllocationInterface.
// A group's client should implement this interface.
type IPAddressAllocationsGetter interface {
	IPAddressAllocations(namespace string) IPAddressAllocationInterface
}

// IPAddressAllocationInterface has methods to work with IPAddressAllocation resources.
type IPAddressAllocationInterface interface {
	Create(ctx context.Context, iPAddressAllocation *vpcv1alpha1.IPAddressAllocation, opts v1.CreateOptions) (*vpcv1alpha1.IPAddressAllocation, error)
	Update(ctx context.Context, iPAddressAllocation *vpcv1alpha1.IPAddressAllocation, opts v1.UpdateOptions) (*vpcv1alpha1.IPAddressAllocation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPAddressAllocation *vpcv1alpha1.IPAddressAllocation, opts v1.UpdateOptions) (*vpcv1alpha1.IPAddressAllocation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.IPAddressAllocation, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.IPAddressAllocationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.IPAddressAllocation, err error)
	IPAddressAllocationExpansion
}

// iPAddressAllocations implements IPAddressAllocationInterface
type iPAddressAllocations struct {
	*gentype.ClientWithList[*vpcv1alpha1.IPAddressAllocation, *vpcv1alpha1.IPAddressAllocationList]
}

// newIPAddressAllocations returns a IPAddressAllocations
func newIPAddressAllocations(c *CrdV1alpha1Client, namespace string) *iPAddressAllocations {
	return &iPAddressAllocations{
		gentype.NewClientWithList[*vpcv1alpha1.IPAddressAllocation, *vpcv1alpha1.IPAddressAllocationList](
			"ipaddressallocations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.IPAddressAllocation { return &vpcv1alpha1.IPAddressAllocation{} },
			func() *vpcv1alpha1.IPAddressAllocationList { return &vpcv1alpha1.IPAddressAllocationList{} },
		),
	}
}
