/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetworkInfosGetter has a method to return a NetworkInfoInterface.
// A group's client should implement this interface.
type NetworkInfosGetter interface {
	NetworkInfos(namespace string) NetworkInfoInterface
}

// NetworkInfoInterface has methods to work with NetworkInfo resources.
type NetworkInfoInterface interface {
	Create(ctx context.Context, networkInfo *vpcv1alpha1.NetworkInfo, opts v1.CreateOptions) (*vpcv1alpha1.NetworkInfo, error)
	Update(ctx context.Context, networkInfo *vpcv1alpha1.NetworkInfo, opts v1.UpdateOptions) (*vpcv1alpha1.NetworkInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.NetworkInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.NetworkInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.NetworkInfo, err error)
	NetworkInfoExpansion
}

// networkInfos implements NetworkInfoInterface
type networkInfos struct {
	*gentype.ClientWithList[*vpcv1alpha1.NetworkInfo, *vpcv1alpha1.NetworkInfoList]
}

// newNetworkInfos returns a NetworkInfos
func newNetworkInfos(c *CrdV1alpha1Client, namespace string) *networkInfos {
	return &networkInfos{
		gentype.NewClientWithList[*vpcv1alpha1.NetworkInfo, *vpcv1alpha1.NetworkInfoList](
			"networkinfos",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.NetworkInfo { return &vpcv1alpha1.NetworkInfo{} },
			func() *vpcv1alpha1.NetworkInfoList { return &vpcv1alpha1.NetworkInfoList{} },
		),
	}
}
