/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetworkResourceTransitionsGetter has a method to return a NetworkResourceTransitionInterface.
// A group's client should implement this interface.
type NetworkResourceTransitionsGetter interface {
	NetworkResourceTransitions() NetworkResourceTransitionInterface
}

// NetworkResourceTransitionInterface has methods to work with NetworkResourceTransition resources.
type NetworkResourceTransitionInterface interface {
	Create(ctx context.Context, networkResourceTransition *vpcv1alpha1.NetworkResourceTransition, opts v1.CreateOptions) (*vpcv1alpha1.NetworkResourceTransition, error)
	Update(ctx context.Context, networkResourceTransition *vpcv1alpha1.NetworkResourceTransition, opts v1.UpdateOptions) (*vpcv1alpha1.NetworkResourceTransition, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, networkResourceTransition *vpcv1alpha1.NetworkResourceTransition, opts v1.UpdateOptions) (*vpcv1alpha1.NetworkResourceTransition, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.NetworkResourceTransition, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.NetworkResourceTransitionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.NetworkResourceTransition, err error)
	NetworkResourceTransitionExpansion
}

// networkResourceTransitions implements NetworkResourceTransitionInterface
type networkResourceTransitions struct {
	*gentype.ClientWithList[*vpcv1alpha1.NetworkResourceTransition, *vpcv1alpha1.NetworkResourceTransitionList]
}

// newNetworkResourceTransitions returns a NetworkResourceTransitions
func newNetworkResourceTransitions(c *CrdV1alpha1Client) *networkResourceTransitions {
	return &networkResourceTransitions{
		gentype.NewClientWithList[*vpcv1alpha1.NetworkResourceTransition, *vpcv1alpha1.NetworkResourceTransitionList](
			"networkresourcetransitions",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *vpcv1alpha1.NetworkResourceTransition { return &vpcv1alpha1.NetworkResourceTransition{} },
			func() *vpcv1alpha1.NetworkResourceTransitionList { return &vpcv1alpha1.NetworkResourceTransitionList{} },
		),
	}
}
