/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SecurityPoliciesGetter has a method to return a SecurityPolicyInterface.
// A group's client should implement this interface.
type SecurityPoliciesGetter interface {
	SecurityPolicies(namespace string) SecurityPolicyInterface
}

// SecurityPolicyInterface has methods to work with SecurityPolicy resources.
type SecurityPolicyInterface interface {
	Create(ctx context.Context, securityPolicy *vpcv1alpha1.SecurityPolicy, opts v1.CreateOptions) (*vpcv1alpha1.SecurityPolicy, error)
	Update(ctx context.Context, securityPolicy *vpcv1alpha1.SecurityPolicy, opts v1.UpdateOptions) (*vpcv1alpha1.SecurityPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, securityPolicy *vpcv1alpha1.SecurityPolicy, opts v1.UpdateOptions) (*vpcv1alpha1.SecurityPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.SecurityPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.SecurityPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.SecurityPolicy, err error)
	SecurityPolicyExpansion
}

// securityPolicies implements SecurityPolicyInterface
type securityPolicies struct {
	*gentype.ClientWithList[*vpcv1alpha1.SecurityPolicy, *vpcv1alpha1.SecurityPolicyList]
}

// newSecurityPolicies returns a SecurityPolicies
func newSecurityPolicies(c *CrdV1alpha1Client, namespace string) *securityPolicies {
	return &securityPolicies{
		gentype.NewClientWithList[*vpcv1alpha1.SecurityPolicy, *vpcv1alpha1.SecurityPolicyList](
			"securitypolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.SecurityPolicy { return &vpcv1alpha1.SecurityPolicy{} },
			func() *vpcv1alpha1.SecurityPolicyList { return &vpcv1alpha1.SecurityPolicyList{} },
		),
	}
}
