/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubnetConnectionBindingMapsGetter has a method to return a SubnetConnectionBindingMapInterface.
// A group's client should implement this interface.
type SubnetConnectionBindingMapsGetter interface {
	SubnetConnectionBindingMaps(namespace string) SubnetConnectionBindingMapInterface
}

// SubnetConnectionBindingMapInterface has methods to work with SubnetConnectionBindingMap resources.
type SubnetConnectionBindingMapInterface interface {
	Create(ctx context.Context, subnetConnectionBindingMap *vpcv1alpha1.SubnetConnectionBindingMap, opts v1.CreateOptions) (*vpcv1alpha1.SubnetConnectionBindingMap, error)
	Update(ctx context.Context, subnetConnectionBindingMap *vpcv1alpha1.SubnetConnectionBindingMap, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetConnectionBindingMap, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnetConnectionBindingMap *vpcv1alpha1.SubnetConnectionBindingMap, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetConnectionBindingMap, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.SubnetConnectionBindingMap, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.SubnetConnectionBindingMapList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.SubnetConnectionBindingMap, err error)
	SubnetConnectionBindingMapExpansion
}

// subnetConnectionBindingMaps implements SubnetConnectionBindingMapInterface
type subnetConnectionBindingMaps struct {
	*gentype.ClientWithList[*vpcv1alpha1.SubnetConnectionBindingMap, *vpcv1alpha1.SubnetConnectionBindingMapList]
}

// newSubnetConnectionBindingMaps returns a SubnetConnectionBindingMaps
func newSubnetConnectionBindingMaps(c *CrdV1alpha1Client, namespace string) *subnetConnectionBindingMaps {
	return &subnetConnectionBindingMaps{
		gentype.NewClientWithList[*vpcv1alpha1.SubnetConnectionBindingMap, *vpcv1alpha1.SubnetConnectionBindingMapList](
			"subnetconnectionbindingmaps",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.SubnetConnectionBindingMap { return &vpcv1alpha1.SubnetConnectionBindingMap{} },
			func() *vpcv1alpha1.SubnetConnectionBindingMapList {
				return &vpcv1alpha1.SubnetConnectionBindingMapList{}
			},
		),
	}
}
