/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubnetSetsGetter has a method to return a SubnetSetInterface.
// A group's client should implement this interface.
type SubnetSetsGetter interface {
	SubnetSets(namespace string) SubnetSetInterface
}

// SubnetSetInterface has methods to work with SubnetSet resources.
type SubnetSetInterface interface {
	Create(ctx context.Context, subnetSet *vpcv1alpha1.SubnetSet, opts v1.CreateOptions) (*vpcv1alpha1.SubnetSet, error)
	Update(ctx context.Context, subnetSet *vpcv1alpha1.SubnetSet, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnetSet *vpcv1alpha1.SubnetSet, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.SubnetSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.SubnetSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.SubnetSet, err error)
	SubnetSetExpansion
}

// subnetSets implements SubnetSetInterface
type subnetSets struct {
	*gentype.ClientWithList[*vpcv1alpha1.SubnetSet, *vpcv1alpha1.SubnetSetList]
}

// newSubnetSets returns a SubnetSets
func newSubnetSets(c *CrdV1alpha1Client, namespace string) *subnetSets {
	return &subnetSets{
		gentype.NewClientWithList[*vpcv1alpha1.SubnetSet, *vpcv1alpha1.SubnetSetList](
			"subnetsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.SubnetSet { return &vpcv1alpha1.SubnetSet{} },
			func() *vpcv1alpha1.SubnetSetList { return &vpcv1alpha1.SubnetSetList{} },
		),
	}
}
