/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubnetIPReservationsGetter has a method to return a SubnetIPReservationInterface.
// A group's client should implement this interface.
type SubnetIPReservationsGetter interface {
	SubnetIPReservations(namespace string) SubnetIPReservationInterface
}

// SubnetIPReservationInterface has methods to work with SubnetIPReservation resources.
type SubnetIPReservationInterface interface {
	Create(ctx context.Context, subnetIPReservation *vpcv1alpha1.SubnetIPReservation, opts v1.CreateOptions) (*vpcv1alpha1.SubnetIPReservation, error)
	Update(ctx context.Context, subnetIPReservation *vpcv1alpha1.SubnetIPReservation, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetIPReservation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnetIPReservation *vpcv1alpha1.SubnetIPReservation, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetIPReservation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.SubnetIPReservation, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.SubnetIPReservationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.SubnetIPReservation, err error)
	SubnetIPReservationExpansion
}

// subnetIPReservations implements SubnetIPReservationInterface
type subnetIPReservations struct {
	*gentype.ClientWithList[*vpcv1alpha1.SubnetIPReservation, *vpcv1alpha1.SubnetIPReservationList]
}

// newSubnetIPReservations returns a SubnetIPReservations
func newSubnetIPReservations(c *CrdV1alpha1Client, namespace string) *subnetIPReservations {
	return &subnetIPReservations{
		gentype.NewClientWithList[*vpcv1alpha1.SubnetIPReservation, *vpcv1alpha1.SubnetIPReservationList](
			"subnetipreservations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.SubnetIPReservation { return &vpcv1alpha1.SubnetIPReservation{} },
			func() *vpcv1alpha1.SubnetIPReservationList { return &vpcv1alpha1.SubnetIPReservationList{} },
		),
	}
}
