/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubnetPortsGetter has a method to return a SubnetPortInterface.
// A group's client should implement this interface.
type SubnetPortsGetter interface {
	SubnetPorts(namespace string) SubnetPortInterface
}

// SubnetPortInterface has methods to work with SubnetPort resources.
type SubnetPortInterface interface {
	Create(ctx context.Context, subnetPort *vpcv1alpha1.SubnetPort, opts v1.CreateOptions) (*vpcv1alpha1.SubnetPort, error)
	Update(ctx context.Context, subnetPort *vpcv1alpha1.SubnetPort, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetPort, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnetPort *vpcv1alpha1.SubnetPort, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetPort, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.SubnetPort, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.SubnetPortList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.SubnetPort, err error)
	SubnetPortExpansion
}

// subnetPorts implements SubnetPortInterface
type subnetPorts struct {
	*gentype.ClientWithList[*vpcv1alpha1.SubnetPort, *vpcv1alpha1.SubnetPortList]
}

// newSubnetPorts returns a SubnetPorts
func newSubnetPorts(c *CrdV1alpha1Client, namespace string) *subnetPorts {
	return &subnetPorts{
		gentype.NewClientWithList[*vpcv1alpha1.SubnetPort, *vpcv1alpha1.SubnetPortList](
			"subnetports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.SubnetPort { return &vpcv1alpha1.SubnetPort{} },
			func() *vpcv1alpha1.SubnetPortList { return &vpcv1alpha1.SubnetPortList{} },
		),
	}
}
