/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SubnetIPReservationsGetter has a method to return a SubnetIPReservationInterface.
// A group's client should implement this interface.
type SubnetIPReservationsGetter interface {
	SubnetIPReservations(namespace string) SubnetIPReservationInterface
}

// SubnetIPReservationInterface has methods to work with SubnetIPReservation resources.
type SubnetIPReservationInterface interface {
	Create(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.CreateOptions) (*v1alpha1.SubnetIPReservation, error)
	Update(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.UpdateOptions) (*v1alpha1.SubnetIPReservation, error)
	UpdateStatus(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.UpdateOptions) (*v1alpha1.SubnetIPReservation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SubnetIPReservation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SubnetIPReservationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubnetIPReservation, err error)
	SubnetIPReservationExpansion
}

// subnetIPReservations implements SubnetIPReservationInterface
type subnetIPReservations struct {
	client rest.Interface
	ns     string
}

// newSubnetIPReservations returns a SubnetIPReservations
func newSubnetIPReservations(c *CrdV1alpha1Client, namespace string) *subnetIPReservations {
	return &subnetIPReservations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the subnetIPReservation, and returns the corresponding subnetIPReservation object, and an error if there is any.
func (c *subnetIPReservations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubnetIPReservation, err error) {
	result = &v1alpha1.SubnetIPReservation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subnetipreservations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SubnetIPReservations that match those selectors.
func (c *subnetIPReservations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubnetIPReservationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SubnetIPReservationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subnetipreservations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested subnetIPReservations.
func (c *subnetIPReservations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("subnetipreservations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a subnetIPReservation and creates it.  Returns the server's representation of the subnetIPReservation, and an error, if there is any.
func (c *subnetIPReservations) Create(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.CreateOptions) (result *v1alpha1.SubnetIPReservation, err error) {
	result = &v1alpha1.SubnetIPReservation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("subnetipreservations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subnetIPReservation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a subnetIPReservation and updates it. Returns the server's representation of the subnetIPReservation, and an error, if there is any.
func (c *subnetIPReservations) Update(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.UpdateOptions) (result *v1alpha1.SubnetIPReservation, err error) {
	result = &v1alpha1.SubnetIPReservation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subnetipreservations").
		Name(subnetIPReservation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subnetIPReservation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *subnetIPReservations) UpdateStatus(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.UpdateOptions) (result *v1alpha1.SubnetIPReservation, err error) {
	result = &v1alpha1.SubnetIPReservation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subnetipreservations").
		Name(subnetIPReservation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subnetIPReservation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the subnetIPReservation and deletes it. Returns an error if one occurs.
func (c *subnetIPReservations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subnetipreservations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *subnetIPReservations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subnetipreservations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched subnetIPReservation.
func (c *subnetIPReservations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubnetIPReservation, err error) {
	result = &v1alpha1.SubnetIPReservation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("subnetipreservations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
