/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubnetPortSettingsGetter has a method to return a SubnetPortSettingInterface.
// A group's client should implement this interface.
type SubnetPortSettingsGetter interface {
	SubnetPortSettings(namespace string) SubnetPortSettingInterface
}

// SubnetPortSettingInterface has methods to work with SubnetPortSetting resources.
type SubnetPortSettingInterface interface {
	Create(ctx context.Context, subnetPortSetting *vpcv1alpha1.SubnetPortSetting, opts v1.CreateOptions) (*vpcv1alpha1.SubnetPortSetting, error)
	Update(ctx context.Context, subnetPortSetting *vpcv1alpha1.SubnetPortSetting, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetPortSetting, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnetPortSetting *vpcv1alpha1.SubnetPortSetting, opts v1.UpdateOptions) (*vpcv1alpha1.SubnetPortSetting, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.SubnetPortSetting, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.SubnetPortSettingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.SubnetPortSetting, err error)
	SubnetPortSettingExpansion
}

// subnetPortSettings implements SubnetPortSettingInterface
type subnetPortSettings struct {
	*gentype.ClientWithList[*vpcv1alpha1.SubnetPortSetting, *vpcv1alpha1.SubnetPortSettingList]
}

// newSubnetPortSettings returns a SubnetPortSettings
func newSubnetPortSettings(c *CrdV1alpha1Client, namespace string) *subnetPortSettings {
	return &subnetPortSettings{
		gentype.NewClientWithList[*vpcv1alpha1.SubnetPortSetting, *vpcv1alpha1.SubnetPortSettingList](
			"subnetportsettings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.SubnetPortSetting { return &vpcv1alpha1.SubnetPortSetting{} },
			func() *vpcv1alpha1.SubnetPortSettingList { return &vpcv1alpha1.SubnetPortSettingList{} },
		),
	}
}
