/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VPCEndpointsGetter has a method to return a VPCEndpointInterface.
// A group's client should implement this interface.
type VPCEndpointsGetter interface {
	VPCEndpoints(namespace string) VPCEndpointInterface
}

// VPCEndpointInterface has methods to work with VPCEndpoint resources.
type VPCEndpointInterface interface {
	Create(ctx context.Context, vPCEndpoint *vpcv1alpha1.VPCEndpoint, opts v1.CreateOptions) (*vpcv1alpha1.VPCEndpoint, error)
	Update(ctx context.Context, vPCEndpoint *vpcv1alpha1.VPCEndpoint, opts v1.UpdateOptions) (*vpcv1alpha1.VPCEndpoint, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vPCEndpoint *vpcv1alpha1.VPCEndpoint, opts v1.UpdateOptions) (*vpcv1alpha1.VPCEndpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vpcv1alpha1.VPCEndpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*vpcv1alpha1.VPCEndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vpcv1alpha1.VPCEndpoint, err error)
	VPCEndpointExpansion
}

// vPCEndpoints implements VPCEndpointInterface
type vPCEndpoints struct {
	*gentype.ClientWithList[*vpcv1alpha1.VPCEndpoint, *vpcv1alpha1.VPCEndpointList]
}

// newVPCEndpoints returns a VPCEndpoints
func newVPCEndpoints(c *CrdV1alpha1Client, namespace string) *vPCEndpoints {
	return &vPCEndpoints{
		gentype.NewClientWithList[*vpcv1alpha1.VPCEndpoint, *vpcv1alpha1.VPCEndpointList](
			"vpcendpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vpcv1alpha1.VPCEndpoint { return &vpcv1alpha1.VPCEndpoint{} },
			func() *vpcv1alpha1.VPCEndpointList { return &vpcv1alpha1.VPCEndpointList{} },
		),
	}
}
