/* Copyright © 2022 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/nsx.vmware.com/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SubnetSetsGetter has a method to return a SubnetSetInterface.
// A group's client should implement this interface.
type SubnetSetsGetter interface {
	SubnetSets(namespace string) SubnetSetInterface
}

// SubnetSetInterface has methods to work with SubnetSet resources.
type SubnetSetInterface interface {
	Create(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.CreateOptions) (*v1alpha1.SubnetSet, error)
	Update(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.UpdateOptions) (*v1alpha1.SubnetSet, error)
	UpdateStatus(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.UpdateOptions) (*v1alpha1.SubnetSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SubnetSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SubnetSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubnetSet, err error)
	SubnetSetExpansion
}

// subnetSets implements SubnetSetInterface
type subnetSets struct {
	client rest.Interface
	ns     string
}

// newSubnetSets returns a SubnetSets
func newSubnetSets(c *NsxV1alpha1Client, namespace string) *subnetSets {
	return &subnetSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the subnetSet, and returns the corresponding subnetSet object, and an error if there is any.
func (c *subnetSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubnetSet, err error) {
	result = &v1alpha1.SubnetSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subnetsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SubnetSets that match those selectors.
func (c *subnetSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubnetSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SubnetSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subnetsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested subnetSets.
func (c *subnetSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("subnetsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a subnetSet and creates it.  Returns the server's representation of the subnetSet, and an error, if there is any.
func (c *subnetSets) Create(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.CreateOptions) (result *v1alpha1.SubnetSet, err error) {
	result = &v1alpha1.SubnetSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("subnetsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subnetSet).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a subnetSet and updates it. Returns the server's representation of the subnetSet, and an error, if there is any.
func (c *subnetSets) Update(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.UpdateOptions) (result *v1alpha1.SubnetSet, err error) {
	result = &v1alpha1.SubnetSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subnetsets").
		Name(subnetSet.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subnetSet).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *subnetSets) UpdateStatus(ctx context.Context, subnetSet *v1alpha1.SubnetSet, opts v1.UpdateOptions) (result *v1alpha1.SubnetSet, err error) {
	result = &v1alpha1.SubnetSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subnetsets").
		Name(subnetSet.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subnetSet).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the subnetSet and deletes it. Returns an error if one occurs.
func (c *subnetSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subnetsets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *subnetSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subnetsets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched subnetSet.
func (c *subnetSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubnetSet, err error) {
	result = &v1alpha1.SubnetSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("subnetsets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
