/* Copyright © 2022 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/nsx.vmware.com/v1alpha1"
	scheme "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VPCsGetter has a method to return a VPCInterface.
// A group's client should implement this interface.
type VPCsGetter interface {
	VPCs(namespace string) VPCInterface
}

// VPCInterface has methods to work with VPC resources.
type VPCInterface interface {
	Create(ctx context.Context, vPC *v1alpha1.VPC, opts v1.CreateOptions) (*v1alpha1.VPC, error)
	Update(ctx context.Context, vPC *v1alpha1.VPC, opts v1.UpdateOptions) (*v1alpha1.VPC, error)
	UpdateStatus(ctx context.Context, vPC *v1alpha1.VPC, opts v1.UpdateOptions) (*v1alpha1.VPC, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VPC, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VPCList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VPC, err error)
	VPCExpansion
}

// vPCs implements VPCInterface
type vPCs struct {
	client rest.Interface
	ns     string
}

// newVPCs returns a VPCs
func newVPCs(c *NsxV1alpha1Client, namespace string) *vPCs {
	return &vPCs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vPC, and returns the corresponding vPC object, and an error if there is any.
func (c *vPCs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VPC, err error) {
	result = &v1alpha1.VPC{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vpcs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VPCs that match those selectors.
func (c *vPCs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VPCList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VPCList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vpcs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vPCs.
func (c *vPCs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vpcs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vPC and creates it.  Returns the server's representation of the vPC, and an error, if there is any.
func (c *vPCs) Create(ctx context.Context, vPC *v1alpha1.VPC, opts v1.CreateOptions) (result *v1alpha1.VPC, err error) {
	result = &v1alpha1.VPC{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vpcs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPC).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vPC and updates it. Returns the server's representation of the vPC, and an error, if there is any.
func (c *vPCs) Update(ctx context.Context, vPC *v1alpha1.VPC, opts v1.UpdateOptions) (result *v1alpha1.VPC, err error) {
	result = &v1alpha1.VPC{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vpcs").
		Name(vPC.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPC).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vPCs) UpdateStatus(ctx context.Context, vPC *v1alpha1.VPC, opts v1.UpdateOptions) (result *v1alpha1.VPC, err error) {
	result = &v1alpha1.VPC{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vpcs").
		Name(vPC.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPC).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vPC and deletes it. Returns an error if one occurs.
func (c *vPCs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vpcs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vPCs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vpcs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vPC.
func (c *vPCs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VPC, err error) {
	result = &v1alpha1.VPC{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vpcs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
