/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubnetSets implements SubnetSetInterface
type fakeSubnetSets struct {
	*gentype.FakeClientWithList[*v1alpha1.SubnetSet, *v1alpha1.SubnetSetList]
	Fake *FakeCrdV1alpha1
}

func newFakeSubnetSets(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.SubnetSetInterface {
	return &fakeSubnetSets{
		gentype.NewFakeClientWithList[*v1alpha1.SubnetSet, *v1alpha1.SubnetSetList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("subnetsets"),
			v1alpha1.SchemeGroupVersion.WithKind("SubnetSet"),
			func() *v1alpha1.SubnetSet { return &v1alpha1.SubnetSet{} },
			func() *v1alpha1.SubnetSetList { return &v1alpha1.SubnetSetList{} },
			func(dst, src *v1alpha1.SubnetSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubnetSetList) []*v1alpha1.SubnetSet { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.SubnetSetList, items []*v1alpha1.SubnetSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
