/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVPCNetworkConfigurations implements VPCNetworkConfigurationInterface
type FakeVPCNetworkConfigurations struct {
	Fake *FakeCrdV1alpha1
}

var vpcnetworkconfigurationsResource = v1alpha1.SchemeGroupVersion.WithResource("vpcnetworkconfigurations")

var vpcnetworkconfigurationsKind = v1alpha1.SchemeGroupVersion.WithKind("VPCNetworkConfiguration")

// Get takes name of the vPCNetworkConfiguration, and returns the corresponding vPCNetworkConfiguration object, and an error if there is any.
func (c *FakeVPCNetworkConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VPCNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(vpcnetworkconfigurationsResource, name), &v1alpha1.VPCNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPCNetworkConfiguration), err
}

// List takes label and field selectors, and returns the list of VPCNetworkConfigurations that match those selectors.
func (c *FakeVPCNetworkConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VPCNetworkConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(vpcnetworkconfigurationsResource, vpcnetworkconfigurationsKind, opts), &v1alpha1.VPCNetworkConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VPCNetworkConfigurationList{ListMeta: obj.(*v1alpha1.VPCNetworkConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.VPCNetworkConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vPCNetworkConfigurations.
func (c *FakeVPCNetworkConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(vpcnetworkconfigurationsResource, opts))
}

// Create takes the representation of a vPCNetworkConfiguration and creates it.  Returns the server's representation of the vPCNetworkConfiguration, and an error, if there is any.
func (c *FakeVPCNetworkConfigurations) Create(ctx context.Context, vPCNetworkConfiguration *v1alpha1.VPCNetworkConfiguration, opts v1.CreateOptions) (result *v1alpha1.VPCNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(vpcnetworkconfigurationsResource, vPCNetworkConfiguration), &v1alpha1.VPCNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPCNetworkConfiguration), err
}

// Update takes the representation of a vPCNetworkConfiguration and updates it. Returns the server's representation of the vPCNetworkConfiguration, and an error, if there is any.
func (c *FakeVPCNetworkConfigurations) Update(ctx context.Context, vPCNetworkConfiguration *v1alpha1.VPCNetworkConfiguration, opts v1.UpdateOptions) (result *v1alpha1.VPCNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(vpcnetworkconfigurationsResource, vPCNetworkConfiguration), &v1alpha1.VPCNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPCNetworkConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVPCNetworkConfigurations) UpdateStatus(ctx context.Context, vPCNetworkConfiguration *v1alpha1.VPCNetworkConfiguration, opts v1.UpdateOptions) (*v1alpha1.VPCNetworkConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(vpcnetworkconfigurationsResource, "status", vPCNetworkConfiguration), &v1alpha1.VPCNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPCNetworkConfiguration), err
}

// Delete takes name of the vPCNetworkConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeVPCNetworkConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(vpcnetworkconfigurationsResource, name, opts), &v1alpha1.VPCNetworkConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVPCNetworkConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(vpcnetworkconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VPCNetworkConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched vPCNetworkConfiguration.
func (c *FakeVPCNetworkConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VPCNetworkConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(vpcnetworkconfigurationsResource, name, pt, data, subresources...), &v1alpha1.VPCNetworkConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPCNetworkConfiguration), err
}
