/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVPCEndpoints implements VPCEndpointInterface
type fakeVPCEndpoints struct {
	*gentype.FakeClientWithList[*v1alpha1.VPCEndpoint, *v1alpha1.VPCEndpointList]
	Fake *FakeCrdV1alpha1
}

func newFakeVPCEndpoints(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.VPCEndpointInterface {
	return &fakeVPCEndpoints{
		gentype.NewFakeClientWithList[*v1alpha1.VPCEndpoint, *v1alpha1.VPCEndpointList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("vpcendpoints"),
			v1alpha1.SchemeGroupVersion.WithKind("VPCEndpoint"),
			func() *v1alpha1.VPCEndpoint { return &v1alpha1.VPCEndpoint{} },
			func() *v1alpha1.VPCEndpointList { return &v1alpha1.VPCEndpointList{} },
			func(dst, src *v1alpha1.VPCEndpointList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VPCEndpointList) []*v1alpha1.VPCEndpoint {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.VPCEndpointList, items []*v1alpha1.VPCEndpoint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
