/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubnetIPReservations implements SubnetIPReservationInterface
type FakeSubnetIPReservations struct {
	Fake *FakeCrdV1alpha1
	ns   string
}

var subnetipreservationsResource = v1alpha1.SchemeGroupVersion.WithResource("subnetipreservations")

var subnetipreservationsKind = v1alpha1.SchemeGroupVersion.WithKind("SubnetIPReservation")

// Get takes name of the subnetIPReservation, and returns the corresponding subnetIPReservation object, and an error if there is any.
func (c *FakeSubnetIPReservations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubnetIPReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(subnetipreservationsResource, c.ns, name), &v1alpha1.SubnetIPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetIPReservation), err
}

// List takes label and field selectors, and returns the list of SubnetIPReservations that match those selectors.
func (c *FakeSubnetIPReservations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubnetIPReservationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(subnetipreservationsResource, subnetipreservationsKind, c.ns, opts), &v1alpha1.SubnetIPReservationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SubnetIPReservationList{ListMeta: obj.(*v1alpha1.SubnetIPReservationList).ListMeta}
	for _, item := range obj.(*v1alpha1.SubnetIPReservationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested subnetIPReservations.
func (c *FakeSubnetIPReservations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(subnetipreservationsResource, c.ns, opts))

}

// Create takes the representation of a subnetIPReservation and creates it.  Returns the server's representation of the subnetIPReservation, and an error, if there is any.
func (c *FakeSubnetIPReservations) Create(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.CreateOptions) (result *v1alpha1.SubnetIPReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(subnetipreservationsResource, c.ns, subnetIPReservation), &v1alpha1.SubnetIPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetIPReservation), err
}

// Update takes the representation of a subnetIPReservation and updates it. Returns the server's representation of the subnetIPReservation, and an error, if there is any.
func (c *FakeSubnetIPReservations) Update(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.UpdateOptions) (result *v1alpha1.SubnetIPReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(subnetipreservationsResource, c.ns, subnetIPReservation), &v1alpha1.SubnetIPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetIPReservation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSubnetIPReservations) UpdateStatus(ctx context.Context, subnetIPReservation *v1alpha1.SubnetIPReservation, opts v1.UpdateOptions) (*v1alpha1.SubnetIPReservation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(subnetipreservationsResource, "status", c.ns, subnetIPReservation), &v1alpha1.SubnetIPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetIPReservation), err
}

// Delete takes name of the subnetIPReservation and deletes it. Returns an error if one occurs.
func (c *FakeSubnetIPReservations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(subnetipreservationsResource, c.ns, name, opts), &v1alpha1.SubnetIPReservation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubnetIPReservations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(subnetipreservationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SubnetIPReservationList{})
	return err
}

// Patch applies the patch and returns the patched subnetIPReservation.
func (c *FakeSubnetIPReservations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubnetIPReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(subnetipreservationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SubnetIPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubnetIPReservation), err
}
