/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubnetConnectionBindingMaps implements SubnetConnectionBindingMapInterface
type fakeSubnetConnectionBindingMaps struct {
	*gentype.FakeClientWithList[*v1alpha1.SubnetConnectionBindingMap, *v1alpha1.SubnetConnectionBindingMapList]
	Fake *FakeCrdV1alpha1
}

func newFakeSubnetConnectionBindingMaps(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.SubnetConnectionBindingMapInterface {
	return &fakeSubnetConnectionBindingMaps{
		gentype.NewFakeClientWithList[*v1alpha1.SubnetConnectionBindingMap, *v1alpha1.SubnetConnectionBindingMapList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("subnetconnectionbindingmaps"),
			v1alpha1.SchemeGroupVersion.WithKind("SubnetConnectionBindingMap"),
			func() *v1alpha1.SubnetConnectionBindingMap { return &v1alpha1.SubnetConnectionBindingMap{} },
			func() *v1alpha1.SubnetConnectionBindingMapList { return &v1alpha1.SubnetConnectionBindingMapList{} },
			func(dst, src *v1alpha1.SubnetConnectionBindingMapList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubnetConnectionBindingMapList) []*v1alpha1.SubnetConnectionBindingMap {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SubnetConnectionBindingMapList, items []*v1alpha1.SubnetConnectionBindingMap) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
