/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAddressBindings implements AddressBindingInterface
type fakeAddressBindings struct {
	*gentype.FakeClientWithList[*v1alpha1.AddressBinding, *v1alpha1.AddressBindingList]
	Fake *FakeCrdV1alpha1
}

func newFakeAddressBindings(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.AddressBindingInterface {
	return &fakeAddressBindings{
		gentype.NewFakeClientWithList[*v1alpha1.AddressBinding, *v1alpha1.AddressBindingList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("addressbindings"),
			v1alpha1.SchemeGroupVersion.WithKind("AddressBinding"),
			func() *v1alpha1.AddressBinding { return &v1alpha1.AddressBinding{} },
			func() *v1alpha1.AddressBindingList { return &v1alpha1.AddressBindingList{} },
			func(dst, src *v1alpha1.AddressBindingList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.AddressBindingList) []*v1alpha1.AddressBinding {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.AddressBindingList, items []*v1alpha1.AddressBinding) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
