/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPBlocksInfos implements IPBlocksInfoInterface
type fakeIPBlocksInfos struct {
	*gentype.FakeClientWithList[*v1alpha1.IPBlocksInfo, *v1alpha1.IPBlocksInfoList]
	Fake *FakeCrdV1alpha1
}

func newFakeIPBlocksInfos(fake *FakeCrdV1alpha1) vpcv1alpha1.IPBlocksInfoInterface {
	return &fakeIPBlocksInfos{
		gentype.NewFakeClientWithList[*v1alpha1.IPBlocksInfo, *v1alpha1.IPBlocksInfoList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("ipblocksinfos"),
			v1alpha1.SchemeGroupVersion.WithKind("IPBlocksInfo"),
			func() *v1alpha1.IPBlocksInfo { return &v1alpha1.IPBlocksInfo{} },
			func() *v1alpha1.IPBlocksInfoList { return &v1alpha1.IPBlocksInfoList{} },
			func(dst, src *v1alpha1.IPBlocksInfoList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPBlocksInfoList) []*v1alpha1.IPBlocksInfo {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IPBlocksInfoList, items []*v1alpha1.IPBlocksInfo) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
