/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubnetPorts implements SubnetPortInterface
type fakeSubnetPorts struct {
	*gentype.FakeClientWithList[*v1alpha1.SubnetPort, *v1alpha1.SubnetPortList]
	Fake *FakeCrdV1alpha1
}

func newFakeSubnetPorts(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.SubnetPortInterface {
	return &fakeSubnetPorts{
		gentype.NewFakeClientWithList[*v1alpha1.SubnetPort, *v1alpha1.SubnetPortList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("subnetports"),
			v1alpha1.SchemeGroupVersion.WithKind("SubnetPort"),
			func() *v1alpha1.SubnetPort { return &v1alpha1.SubnetPort{} },
			func() *v1alpha1.SubnetPortList { return &v1alpha1.SubnetPortList{} },
			func(dst, src *v1alpha1.SubnetPortList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubnetPortList) []*v1alpha1.SubnetPort { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.SubnetPortList, items []*v1alpha1.SubnetPort) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
