/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetworkInfos implements NetworkInfoInterface
type fakeNetworkInfos struct {
	*gentype.FakeClientWithList[*v1alpha1.NetworkInfo, *v1alpha1.NetworkInfoList]
	Fake *FakeCrdV1alpha1
}

func newFakeNetworkInfos(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.NetworkInfoInterface {
	return &fakeNetworkInfos{
		gentype.NewFakeClientWithList[*v1alpha1.NetworkInfo, *v1alpha1.NetworkInfoList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("networkinfos"),
			v1alpha1.SchemeGroupVersion.WithKind("NetworkInfo"),
			func() *v1alpha1.NetworkInfo { return &v1alpha1.NetworkInfo{} },
			func() *v1alpha1.NetworkInfoList { return &v1alpha1.NetworkInfoList{} },
			func(dst, src *v1alpha1.NetworkInfoList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NetworkInfoList) []*v1alpha1.NetworkInfo {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.NetworkInfoList, items []*v1alpha1.NetworkInfo) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
