/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVPCNetworkConfigurations implements VPCNetworkConfigurationInterface
type fakeVPCNetworkConfigurations struct {
	*gentype.FakeClientWithList[*v1alpha1.VPCNetworkConfiguration, *v1alpha1.VPCNetworkConfigurationList]
	Fake *FakeCrdV1alpha1
}

func newFakeVPCNetworkConfigurations(fake *FakeCrdV1alpha1) vpcv1alpha1.VPCNetworkConfigurationInterface {
	return &fakeVPCNetworkConfigurations{
		gentype.NewFakeClientWithList[*v1alpha1.VPCNetworkConfiguration, *v1alpha1.VPCNetworkConfigurationList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("vpcnetworkconfigurations"),
			v1alpha1.SchemeGroupVersion.WithKind("VPCNetworkConfiguration"),
			func() *v1alpha1.VPCNetworkConfiguration { return &v1alpha1.VPCNetworkConfiguration{} },
			func() *v1alpha1.VPCNetworkConfigurationList { return &v1alpha1.VPCNetworkConfigurationList{} },
			func(dst, src *v1alpha1.VPCNetworkConfigurationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VPCNetworkConfigurationList) []*v1alpha1.VPCNetworkConfiguration {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.VPCNetworkConfigurationList, items []*v1alpha1.VPCNetworkConfiguration) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
