/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPAddressAllocations implements IPAddressAllocationInterface
type fakeIPAddressAllocations struct {
	*gentype.FakeClientWithList[*v1alpha1.IPAddressAllocation, *v1alpha1.IPAddressAllocationList]
	Fake *FakeCrdV1alpha1
}

func newFakeIPAddressAllocations(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.IPAddressAllocationInterface {
	return &fakeIPAddressAllocations{
		gentype.NewFakeClientWithList[*v1alpha1.IPAddressAllocation, *v1alpha1.IPAddressAllocationList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ipaddressallocations"),
			v1alpha1.SchemeGroupVersion.WithKind("IPAddressAllocation"),
			func() *v1alpha1.IPAddressAllocation { return &v1alpha1.IPAddressAllocation{} },
			func() *v1alpha1.IPAddressAllocationList { return &v1alpha1.IPAddressAllocationList{} },
			func(dst, src *v1alpha1.IPAddressAllocationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPAddressAllocationList) []*v1alpha1.IPAddressAllocation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IPAddressAllocationList, items []*v1alpha1.IPAddressAllocation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
