/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubnetPortSettings implements SubnetPortSettingInterface
type fakeSubnetPortSettings struct {
	*gentype.FakeClientWithList[*v1alpha1.SubnetPortSetting, *v1alpha1.SubnetPortSettingList]
	Fake *FakeCrdV1alpha1
}

func newFakeSubnetPortSettings(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.SubnetPortSettingInterface {
	return &fakeSubnetPortSettings{
		gentype.NewFakeClientWithList[*v1alpha1.SubnetPortSetting, *v1alpha1.SubnetPortSettingList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("subnetportsettings"),
			v1alpha1.SchemeGroupVersion.WithKind("SubnetPortSetting"),
			func() *v1alpha1.SubnetPortSetting { return &v1alpha1.SubnetPortSetting{} },
			func() *v1alpha1.SubnetPortSettingList { return &v1alpha1.SubnetPortSettingList{} },
			func(dst, src *v1alpha1.SubnetPortSettingList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubnetPortSettingList) []*v1alpha1.SubnetPortSetting {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SubnetPortSettingList, items []*v1alpha1.SubnetPortSetting) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
