/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubnetIPReservations implements SubnetIPReservationInterface
type fakeSubnetIPReservations struct {
	*gentype.FakeClientWithList[*v1alpha1.SubnetIPReservation, *v1alpha1.SubnetIPReservationList]
	Fake *FakeCrdV1alpha1
}

func newFakeSubnetIPReservations(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.SubnetIPReservationInterface {
	return &fakeSubnetIPReservations{
		gentype.NewFakeClientWithList[*v1alpha1.SubnetIPReservation, *v1alpha1.SubnetIPReservationList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("subnetipreservations"),
			v1alpha1.SchemeGroupVersion.WithKind("SubnetIPReservation"),
			func() *v1alpha1.SubnetIPReservation { return &v1alpha1.SubnetIPReservation{} },
			func() *v1alpha1.SubnetIPReservationList { return &v1alpha1.SubnetIPReservationList{} },
			func(dst, src *v1alpha1.SubnetIPReservationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubnetIPReservationList) []*v1alpha1.SubnetIPReservation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SubnetIPReservationList, items []*v1alpha1.SubnetIPReservation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
