/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeStaticRoutes implements StaticRouteInterface
type fakeStaticRoutes struct {
	*gentype.FakeClientWithList[*v1alpha1.StaticRoute, *v1alpha1.StaticRouteList]
	Fake *FakeCrdV1alpha1
}

func newFakeStaticRoutes(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.StaticRouteInterface {
	return &fakeStaticRoutes{
		gentype.NewFakeClientWithList[*v1alpha1.StaticRoute, *v1alpha1.StaticRouteList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("staticroutes"),
			v1alpha1.SchemeGroupVersion.WithKind("StaticRoute"),
			func() *v1alpha1.StaticRoute { return &v1alpha1.StaticRoute{} },
			func() *v1alpha1.StaticRouteList { return &v1alpha1.StaticRouteList{} },
			func(dst, src *v1alpha1.StaticRouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.StaticRouteList) []*v1alpha1.StaticRoute {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.StaticRouteList, items []*v1alpha1.StaticRoute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
