/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/vpc/v1alpha1"
	vpcv1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/client/clientset/versioned/typed/vpc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeServiceEndpoints implements ServiceEndpointInterface
type fakeServiceEndpoints struct {
	*gentype.FakeClientWithList[*v1alpha1.ServiceEndpoint, *v1alpha1.ServiceEndpointList]
	Fake *FakeCrdV1alpha1
}

func newFakeServiceEndpoints(fake *FakeCrdV1alpha1, namespace string) vpcv1alpha1.ServiceEndpointInterface {
	return &fakeServiceEndpoints{
		gentype.NewFakeClientWithList[*v1alpha1.ServiceEndpoint, *v1alpha1.ServiceEndpointList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("serviceendpoints"),
			v1alpha1.SchemeGroupVersion.WithKind("ServiceEndpoint"),
			func() *v1alpha1.ServiceEndpoint { return &v1alpha1.ServiceEndpoint{} },
			func() *v1alpha1.ServiceEndpointList { return &v1alpha1.ServiceEndpointList{} },
			func(dst, src *v1alpha1.ServiceEndpointList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ServiceEndpointList) []*v1alpha1.ServiceEndpoint {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ServiceEndpointList, items []*v1alpha1.ServiceEndpoint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
