//go:build !ignore_autogenerated

/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocatedByVPC) DeepCopyInto(out *AllocatedByVPC) {
	*out = *in
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]VPCIPAddress, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocatedByVPC.
func (in *AllocatedByVPC) DeepCopy() *AllocatedByVPC {
	if in == nil {
		return nil
	}
	out := new(AllocatedByVPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIDRUsage) DeepCopyInto(out *CIDRUsage) {
	*out = *in
	in.UsageDetails.DeepCopyInto(&out.UsageDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIDRUsage.
func (in *CIDRUsage) DeepCopy() *CIDRUsage {
	if in == nil {
		return nil
	}
	out := new(CIDRUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DhcpIpPoolUsage) DeepCopyInto(out *DhcpIpPoolUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DhcpIpPoolUsage.
func (in *DhcpIpPoolUsage) DeepCopy() *DhcpIpPoolUsage {
	if in == nil {
		return nil
	}
	out := new(DhcpIpPoolUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPBlockUsage) DeepCopyInto(out *IPBlockUsage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.UsedIPRanges != nil {
		in, out := &in.UsedIPRanges, &out.UsedIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AvailableIPRanges != nil {
		in, out := &in.AvailableIPRanges, &out.AvailableIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CIDRUsages != nil {
		in, out := &in.CIDRUsages, &out.CIDRUsages
		*out = make([]CIDRUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RangeUsages != nil {
		in, out := &in.RangeUsages, &out.RangeUsages
		*out = make([]RangeUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPBlockUsage.
func (in *IPBlockUsage) DeepCopy() *IPBlockUsage {
	if in == nil {
		return nil
	}
	out := new(IPBlockUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPBlockUsage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPoolRange) DeepCopyInto(out *IPPoolRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPoolRange.
func (in *IPPoolRange) DeepCopy() *IPPoolRange {
	if in == nil {
		return nil
	}
	out := new(IPPoolRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolUsage) DeepCopyInto(out *PoolUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolUsage.
func (in *PoolUsage) DeepCopy() *PoolUsage {
	if in == nil {
		return nil
	}
	out := new(PoolUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangeUsage) DeepCopyInto(out *RangeUsage) {
	*out = *in
	in.UsageDetails.DeepCopyInto(&out.UsageDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangeUsage.
func (in *RangeUsage) DeepCopy() *RangeUsage {
	if in == nil {
		return nil
	}
	out := new(RangeUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetDHCPServerConfigStats) DeepCopyInto(out *SubnetDHCPServerConfigStats) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetDHCPServerConfigStats.
func (in *SubnetDHCPServerConfigStats) DeepCopy() *SubnetDHCPServerConfigStats {
	if in == nil {
		return nil
	}
	out := new(SubnetDHCPServerConfigStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetDHCPServerConfigStats) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetDHCPServerConfigStatsList) DeepCopyInto(out *SubnetDHCPServerConfigStatsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubnetDHCPServerConfigStats, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetDHCPServerConfigStatsList.
func (in *SubnetDHCPServerConfigStatsList) DeepCopy() *SubnetDHCPServerConfigStatsList {
	if in == nil {
		return nil
	}
	out := new(SubnetDHCPServerConfigStatsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetDHCPServerConfigStatsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetDHCPServerConfigStatsSpec) DeepCopyInto(out *SubnetDHCPServerConfigStatsSpec) {
	*out = *in
	if in.IpPoolStats != nil {
		in, out := &in.IpPoolStats, &out.IpPoolStats
		*out = make([]DhcpIpPoolUsage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetDHCPServerConfigStatsSpec.
func (in *SubnetDHCPServerConfigStatsSpec) DeepCopy() *SubnetDHCPServerConfigStatsSpec {
	if in == nil {
		return nil
	}
	out := new(SubnetDHCPServerConfigStatsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetIPPoolSpec) DeepCopyInto(out *SubnetIPPoolSpec) {
	*out = *in
	if in.PoolUsage != nil {
		in, out := &in.PoolUsage, &out.PoolUsage
		*out = new(PoolUsage)
		**out = **in
	}
	if in.PoolSubnets != nil {
		in, out := &in.PoolSubnets, &out.PoolSubnets
		*out = make([]SubnetIPPoolSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetIPPoolSpec.
func (in *SubnetIPPoolSpec) DeepCopy() *SubnetIPPoolSpec {
	if in == nil {
		return nil
	}
	out := new(SubnetIPPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetIPPoolSubnet) DeepCopyInto(out *SubnetIPPoolSubnet) {
	*out = *in
	if in.AllocationRanges != nil {
		in, out := &in.AllocationRanges, &out.AllocationRanges
		*out = make([]IPPoolRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetIPPoolSubnet.
func (in *SubnetIPPoolSubnet) DeepCopy() *SubnetIPPoolSubnet {
	if in == nil {
		return nil
	}
	out := new(SubnetIPPoolSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetIPPools) DeepCopyInto(out *SubnetIPPools) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetIPPools.
func (in *SubnetIPPools) DeepCopy() *SubnetIPPools {
	if in == nil {
		return nil
	}
	out := new(SubnetIPPools)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetIPPools) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetIPPoolsList) DeepCopyInto(out *SubnetIPPoolsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubnetIPPools, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetIPPoolsList.
func (in *SubnetIPPoolsList) DeepCopy() *SubnetIPPoolsList {
	if in == nil {
		return nil
	}
	out := new(SubnetIPPoolsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetIPPoolsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageDetails) DeepCopyInto(out *UsageDetails) {
	*out = *in
	if in.UsedIPRanges != nil {
		in, out := &in.UsedIPRanges, &out.UsedIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OverallUsedIPRanges != nil {
		in, out := &in.OverallUsedIPRanges, &out.OverallUsedIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AvailableIPRanges != nil {
		in, out := &in.AvailableIPRanges, &out.AvailableIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageDetails.
func (in *UsageDetails) DeepCopy() *UsageDetails {
	if in == nil {
		return nil
	}
	out := new(UsageDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCIPAddress) DeepCopyInto(out *VPCIPAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCIPAddress.
func (in *VPCIPAddress) DeepCopy() *VPCIPAddress {
	if in == nil {
		return nil
	}
	out := new(VPCIPAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCIPAddressBlock) DeepCopyInto(out *VPCIPAddressBlock) {
	*out = *in
	in.AllocatedByVPC.DeepCopyInto(&out.AllocatedByVPC)
	if in.CIDRs != nil {
		in, out := &in.CIDRs, &out.CIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]IPPoolRange, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedIPs != nil {
		in, out := &in.ExcludedIPs, &out.ExcludedIPs
		*out = make([]IPPoolRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCIPAddressBlock.
func (in *VPCIPAddressBlock) DeepCopy() *VPCIPAddressBlock {
	if in == nil {
		return nil
	}
	out := new(VPCIPAddressBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCIPAddressUsage) DeepCopyInto(out *VPCIPAddressUsage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.IPBlocks != nil {
		in, out := &in.IPBlocks, &out.IPBlocks
		*out = make([]VPCIPAddressBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCIPAddressUsage.
func (in *VPCIPAddressUsage) DeepCopy() *VPCIPAddressUsage {
	if in == nil {
		return nil
	}
	out := new(VPCIPAddressUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCIPAddressUsage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
