//go:build !ignore_autogenerated

/* Copyright © 2024 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocatedByVpc) DeepCopyInto(out *AllocatedByVpc) {
	*out = *in
	if in.IpAddresses != nil {
		in, out := &in.IpAddresses, &out.IpAddresses
		*out = make([]VpcIpAddress, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocatedByVpc.
func (in *AllocatedByVpc) DeepCopy() *AllocatedByVpc {
	if in == nil {
		return nil
	}
	out := new(AllocatedByVpc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CidrUsageDetails) DeepCopyInto(out *CidrUsageDetails) {
	*out = *in
	if in.AvailableIpRanges != nil {
		in, out := &in.AvailableIpRanges, &out.AvailableIpRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UsedIpRanges != nil {
		in, out := &in.UsedIpRanges, &out.UsedIpRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CidrUsageDetails.
func (in *CidrUsageDetails) DeepCopy() *CidrUsageDetails {
	if in == nil {
		return nil
	}
	out := new(CidrUsageDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DhcpIpPoolUsage) DeepCopyInto(out *DhcpIpPoolUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DhcpIpPoolUsage.
func (in *DhcpIpPoolUsage) DeepCopy() *DhcpIpPoolUsage {
	if in == nil {
		return nil
	}
	out := new(DhcpIpPoolUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPBlockUsage) DeepCopyInto(out *IPBlockUsage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPBlockUsage.
func (in *IPBlockUsage) DeepCopy() *IPBlockUsage {
	if in == nil {
		return nil
	}
	out := new(IPBlockUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPBlockUsage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPBlockUsageList) DeepCopyInto(out *IPBlockUsageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPBlockUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPBlockUsageList.
func (in *IPBlockUsageList) DeepCopy() *IPBlockUsageList {
	if in == nil {
		return nil
	}
	out := new(IPBlockUsageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPBlockUsageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPBlockUsageSpec) DeepCopyInto(out *IPBlockUsageSpec) {
	*out = *in
	if in.AvailableIpRanges != nil {
		in, out := &in.AvailableIpRanges, &out.AvailableIpRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CidrUsage != nil {
		in, out := &in.CidrUsage, &out.CidrUsage
		*out = make([]CidrUsageDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RangeUsage != nil {
		in, out := &in.RangeUsage, &out.RangeUsage
		*out = make([]RangeUsageDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UsedIpRanges != nil {
		in, out := &in.UsedIpRanges, &out.UsedIpRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPBlockUsageSpec.
func (in *IPBlockUsageSpec) DeepCopy() *IPBlockUsageSpec {
	if in == nil {
		return nil
	}
	out := new(IPBlockUsageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpPoolRange) DeepCopyInto(out *IpPoolRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpPoolRange.
func (in *IpPoolRange) DeepCopy() *IpPoolRange {
	if in == nil {
		return nil
	}
	out := new(IpPoolRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolUsage) DeepCopyInto(out *PoolUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolUsage.
func (in *PoolUsage) DeepCopy() *PoolUsage {
	if in == nil {
		return nil
	}
	out := new(PoolUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangeUsageDetails) DeepCopyInto(out *RangeUsageDetails) {
	*out = *in
	if in.AvailableIpRanges != nil {
		in, out := &in.AvailableIpRanges, &out.AvailableIpRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UsedIpRanges != nil {
		in, out := &in.UsedIpRanges, &out.UsedIpRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangeUsageDetails.
func (in *RangeUsageDetails) DeepCopy() *RangeUsageDetails {
	if in == nil {
		return nil
	}
	out := new(RangeUsageDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetDHCPServerConfigStats) DeepCopyInto(out *SubnetDHCPServerConfigStats) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetDHCPServerConfigStats.
func (in *SubnetDHCPServerConfigStats) DeepCopy() *SubnetDHCPServerConfigStats {
	if in == nil {
		return nil
	}
	out := new(SubnetDHCPServerConfigStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetDHCPServerConfigStats) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetDHCPServerConfigStatsList) DeepCopyInto(out *SubnetDHCPServerConfigStatsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubnetDHCPServerConfigStats, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetDHCPServerConfigStatsList.
func (in *SubnetDHCPServerConfigStatsList) DeepCopy() *SubnetDHCPServerConfigStatsList {
	if in == nil {
		return nil
	}
	out := new(SubnetDHCPServerConfigStatsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetDHCPServerConfigStatsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetDHCPServerConfigStatsSpec) DeepCopyInto(out *SubnetDHCPServerConfigStatsSpec) {
	*out = *in
	if in.IpPoolStats != nil {
		in, out := &in.IpPoolStats, &out.IpPoolStats
		*out = make([]DhcpIpPoolUsage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetDHCPServerConfigStatsSpec.
func (in *SubnetDHCPServerConfigStatsSpec) DeepCopy() *SubnetDHCPServerConfigStatsSpec {
	if in == nil {
		return nil
	}
	out := new(SubnetDHCPServerConfigStatsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetIPPoolSpec) DeepCopyInto(out *SubnetIPPoolSpec) {
	*out = *in
	if in.PoolUsage != nil {
		in, out := &in.PoolUsage, &out.PoolUsage
		*out = new(PoolUsage)
		**out = **in
	}
	if in.PoolSubnets != nil {
		in, out := &in.PoolSubnets, &out.PoolSubnets
		*out = make([]SubnetIPPoolSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetIPPoolSpec.
func (in *SubnetIPPoolSpec) DeepCopy() *SubnetIPPoolSpec {
	if in == nil {
		return nil
	}
	out := new(SubnetIPPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetIPPoolSubnet) DeepCopyInto(out *SubnetIPPoolSubnet) {
	*out = *in
	if in.AllocationRanges != nil {
		in, out := &in.AllocationRanges, &out.AllocationRanges
		*out = make([]IpPoolRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetIPPoolSubnet.
func (in *SubnetIPPoolSubnet) DeepCopy() *SubnetIPPoolSubnet {
	if in == nil {
		return nil
	}
	out := new(SubnetIPPoolSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetIPPools) DeepCopyInto(out *SubnetIPPools) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetIPPools.
func (in *SubnetIPPools) DeepCopy() *SubnetIPPools {
	if in == nil {
		return nil
	}
	out := new(SubnetIPPools)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetIPPools) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetIPPoolsList) DeepCopyInto(out *SubnetIPPoolsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubnetIPPools, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetIPPoolsList.
func (in *SubnetIPPoolsList) DeepCopy() *SubnetIPPoolsList {
	if in == nil {
		return nil
	}
	out := new(SubnetIPPoolsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubnetIPPoolsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCIPAddressUsage) DeepCopyInto(out *VPCIPAddressUsage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCIPAddressUsage.
func (in *VPCIPAddressUsage) DeepCopy() *VPCIPAddressUsage {
	if in == nil {
		return nil
	}
	out := new(VPCIPAddressUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCIPAddressUsage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCIPAddressUsageList) DeepCopyInto(out *VPCIPAddressUsageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCIPAddressUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCIPAddressUsageList.
func (in *VPCIPAddressUsageList) DeepCopy() *VPCIPAddressUsageList {
	if in == nil {
		return nil
	}
	out := new(VPCIPAddressUsageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCIPAddressUsageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCIPAddressUsageSpec) DeepCopyInto(out *VPCIPAddressUsageSpec) {
	*out = *in
	if in.IpBlocks != nil {
		in, out := &in.IpBlocks, &out.IpBlocks
		*out = make([]VpcIpAddressBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCIPAddressUsageSpec.
func (in *VPCIPAddressUsageSpec) DeepCopy() *VPCIPAddressUsageSpec {
	if in == nil {
		return nil
	}
	out := new(VPCIPAddressUsageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcIpAddress) DeepCopyInto(out *VpcIpAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcIpAddress.
func (in *VpcIpAddress) DeepCopy() *VpcIpAddress {
	if in == nil {
		return nil
	}
	out := new(VpcIpAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcIpAddressBlock) DeepCopyInto(out *VpcIpAddressBlock) {
	*out = *in
	if in.AllocatedByVpc != nil {
		in, out := &in.AllocatedByVpc, &out.AllocatedByVpc
		*out = new(AllocatedByVpc)
		(*in).DeepCopyInto(*out)
	}
	if in.Cidrs != nil {
		in, out := &in.Cidrs, &out.Cidrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedIps != nil {
		in, out := &in.ExcludedIps, &out.ExcludedIps
		*out = make([]IpPoolRange, len(*in))
		copy(*out, *in)
	}
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]IpPoolRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcIpAddressBlock.
func (in *VpcIpAddressBlock) DeepCopy() *VpcIpAddressBlock {
	if in == nil {
		return nil
	}
	out := new(VpcIpAddressBlock)
	in.DeepCopyInto(out)
	return out
}
