/* Copyright © 2022 VMware, Inc. All Rights Reserved.
   SPDX-License-Identifier: Apache-2.0 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/nsx-operator/pkg/apis/nsx.vmware.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VPCNetworkConfigurationLister helps list VPCNetworkConfigurations.
// All objects returned here must be treated as read-only.
type VPCNetworkConfigurationLister interface {
	// List lists all VPCNetworkConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.VPCNetworkConfiguration, err error)
	// VPCNetworkConfigurations returns an object that can list and get VPCNetworkConfigurations.
	VPCNetworkConfigurations(namespace string) VPCNetworkConfigurationNamespaceLister
	VPCNetworkConfigurationListerExpansion
}

// vPCNetworkConfigurationLister implements the VPCNetworkConfigurationLister interface.
type vPCNetworkConfigurationLister struct {
	indexer cache.Indexer
}

// NewVPCNetworkConfigurationLister returns a new VPCNetworkConfigurationLister.
func NewVPCNetworkConfigurationLister(indexer cache.Indexer) VPCNetworkConfigurationLister {
	return &vPCNetworkConfigurationLister{indexer: indexer}
}

// List lists all VPCNetworkConfigurations in the indexer.
func (s *vPCNetworkConfigurationLister) List(selector labels.Selector) (ret []*v1alpha1.VPCNetworkConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VPCNetworkConfiguration))
	})
	return ret, err
}

// VPCNetworkConfigurations returns an object that can list and get VPCNetworkConfigurations.
func (s *vPCNetworkConfigurationLister) VPCNetworkConfigurations(namespace string) VPCNetworkConfigurationNamespaceLister {
	return vPCNetworkConfigurationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VPCNetworkConfigurationNamespaceLister helps list and get VPCNetworkConfigurations.
// All objects returned here must be treated as read-only.
type VPCNetworkConfigurationNamespaceLister interface {
	// List lists all VPCNetworkConfigurations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.VPCNetworkConfiguration, err error)
	// Get retrieves the VPCNetworkConfiguration from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.VPCNetworkConfiguration, error)
	VPCNetworkConfigurationNamespaceListerExpansion
}

// vPCNetworkConfigurationNamespaceLister implements the VPCNetworkConfigurationNamespaceLister
// interface.
type vPCNetworkConfigurationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VPCNetworkConfigurations in the indexer for a given namespace.
func (s vPCNetworkConfigurationNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.VPCNetworkConfiguration, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VPCNetworkConfiguration))
	})
	return ret, err
}

// Get retrieves the VPCNetworkConfiguration from the indexer for a given namespace and name.
func (s vPCNetworkConfigurationNamespaceLister) Get(name string) (*v1alpha1.VPCNetworkConfiguration, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("vpcnetworkconfiguration"), name)
	}
	return obj.(*v1alpha1.VPCNetworkConfiguration), nil
}
