// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware-tanzu/nsx-operator/pkg/controllers/gateway (interfaces: StatusUpdater)

// Package mockgateway is a generated GoMock package.
package mockgateway

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/vmware-tanzu/nsx-operator/pkg/controllers/common"
	types "k8s.io/apimachinery/pkg/types"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockStatusUpdater is a mock of StatusUpdater interface.
type MockStatusUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockStatusUpdaterMockRecorder
}

// MockStatusUpdaterMockRecorder is the mock recorder for MockStatusUpdater.
type MockStatusUpdaterMockRecorder struct {
	mock *MockStatusUpdater
}

// NewMockStatusUpdater creates a new mock instance.
func NewMockStatusUpdater(ctrl *gomock.Controller) *MockStatusUpdater {
	mock := &MockStatusUpdater{ctrl: ctrl}
	mock.recorder = &MockStatusUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusUpdater) EXPECT() *MockStatusUpdaterMockRecorder {
	return m.recorder
}

// DeleteFail mocks base method.
func (m *MockStatusUpdater) DeleteFail(arg0 types.NamespacedName, arg1 client.Object, arg2 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteFail", arg0, arg1, arg2)
}

// DeleteFail indicates an expected call of DeleteFail.
func (mr *MockStatusUpdaterMockRecorder) DeleteFail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFail", reflect.TypeOf((*MockStatusUpdater)(nil).DeleteFail), arg0, arg1, arg2)
}

// DeleteSuccess mocks base method.
func (m *MockStatusUpdater) DeleteSuccess(arg0 types.NamespacedName, arg1 client.Object) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteSuccess", arg0, arg1)
}

// DeleteSuccess indicates an expected call of DeleteSuccess.
func (mr *MockStatusUpdaterMockRecorder) DeleteSuccess(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSuccess", reflect.TypeOf((*MockStatusUpdater)(nil).DeleteSuccess), arg0, arg1)
}

// IncreaseDeleteFailTotal mocks base method.
func (m *MockStatusUpdater) IncreaseDeleteFailTotal() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseDeleteFailTotal")
}

// IncreaseDeleteFailTotal indicates an expected call of IncreaseDeleteFailTotal.
func (mr *MockStatusUpdaterMockRecorder) IncreaseDeleteFailTotal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseDeleteFailTotal", reflect.TypeOf((*MockStatusUpdater)(nil).IncreaseDeleteFailTotal))
}

// IncreaseDeleteSuccessTotal mocks base method.
func (m *MockStatusUpdater) IncreaseDeleteSuccessTotal() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseDeleteSuccessTotal")
}

// IncreaseDeleteSuccessTotal indicates an expected call of IncreaseDeleteSuccessTotal.
func (mr *MockStatusUpdaterMockRecorder) IncreaseDeleteSuccessTotal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseDeleteSuccessTotal", reflect.TypeOf((*MockStatusUpdater)(nil).IncreaseDeleteSuccessTotal))
}

// IncreaseDeleteTotal mocks base method.
func (m *MockStatusUpdater) IncreaseDeleteTotal() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseDeleteTotal")
}

// IncreaseDeleteTotal indicates an expected call of IncreaseDeleteTotal.
func (mr *MockStatusUpdaterMockRecorder) IncreaseDeleteTotal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseDeleteTotal", reflect.TypeOf((*MockStatusUpdater)(nil).IncreaseDeleteTotal))
}

// IncreaseSyncTotal mocks base method.
func (m *MockStatusUpdater) IncreaseSyncTotal() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseSyncTotal")
}

// IncreaseSyncTotal indicates an expected call of IncreaseSyncTotal.
func (mr *MockStatusUpdaterMockRecorder) IncreaseSyncTotal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseSyncTotal", reflect.TypeOf((*MockStatusUpdater)(nil).IncreaseSyncTotal))
}

// IncreaseUpdateTotal mocks base method.
func (m *MockStatusUpdater) IncreaseUpdateTotal() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseUpdateTotal")
}

// IncreaseUpdateTotal indicates an expected call of IncreaseUpdateTotal.
func (mr *MockStatusUpdaterMockRecorder) IncreaseUpdateTotal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseUpdateTotal", reflect.TypeOf((*MockStatusUpdater)(nil).IncreaseUpdateTotal))
}

// UpdateFail mocks base method.
func (m *MockStatusUpdater) UpdateFail(arg0 context.Context, arg1 client.Object, arg2 error, arg3 string, arg4 common.UpdateFailStatusFn, arg5 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3, arg4}
	for _, a := range arg5 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "UpdateFail", varargs...)
}

// UpdateFail indicates an expected call of UpdateFail.
func (mr *MockStatusUpdaterMockRecorder) UpdateFail(arg0, arg1, arg2, arg3, arg4 interface{}, arg5 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3, arg4}, arg5...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFail", reflect.TypeOf((*MockStatusUpdater)(nil).UpdateFail), varargs...)
}

// UpdateSuccess mocks base method.
func (m *MockStatusUpdater) UpdateSuccess(arg0 context.Context, arg1 client.Object, arg2 common.UpdateSuccessStatusFn, arg3 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "UpdateSuccess", varargs...)
}

// UpdateSuccess indicates an expected call of UpdateSuccess.
func (mr *MockStatusUpdaterMockRecorder) UpdateSuccess(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSuccess", reflect.TypeOf((*MockStatusUpdater)(nil).UpdateSuccess), varargs...)
}
