name: Makefile CI

on:
  push:
    branches: [ vpc_dev ]
  pull_request:
    branches: [ vpc_dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
        
    - name: Run build
      run: make build

    - name: Run test
      run: make test
